const assert = require('node:assert/strict');
const fs = require('node:fs');

const source = fs.readFileSync('app.js', 'utf8');
const markup = fs.readFileSync('index.html', 'utf8');

assert.match(source, /function normalizeStatus/);
assert.match(source, /function normalizePriority/);
assert.match(source, /function isDailyDone/);
assert.match(source, /function removeDefaultSheets/);
assert.match(source, /showSaveFilePicker/);
assert.match(source, /requestPermission/);
assert.match(source, /loadMoreDoneButton/);
assert.match(source, /priorityFilter/);
assert.match(source, /sortFilter/);
assert.match(markup, /daily-progress/);
assert.match(source, /hasUnsavedChanges/);
assert.match(source, /Perubahan belum disimpan akan diganti/);
assert.match(source, /downloadWorkbook/);
assert.match(source, /removeDefaultSheets/);
assert.match(source, /loadActivitiesFromFile/);
assert.match(source, /Details/);
assert.match(source, /Workbook di-load/);
assert.match(source, /Workbook disimpan/);
assert.doesNotMatch(source, /activities = activities\.slice\(0, 100\)/);
assert.match(markup, /activeFileName/);
assert.match(markup, /saveState/);
assert.match(source, /renderTitleSuggestions/);
assert.match(markup, /titleSuggestions/);
assert.match(source, /completionDuration/);
assert.match(source, /completedAt/);
assert.match(source, /openNoteDialog/);
assert.match(source, /subitemDialog/);
assert.match(source, /Subitem ditambahkan/);
assert.match(source, /renderSubitemCells/);
assert.match(source, /renderInlineSubitems/);
assert.match(source, /subitem-inline/);
assert.match(source, /item\.subitems = Array\.isArray/);
assert.match(source, /Note/);
assert.match(source, /has-note/);
assert.match(markup, /noteDialog/);
assert.match(markup, /editNoteInput/);
assert.match(markup, /On revision/);
assert.match(markup, /Waiting for requester review/);
assert.match(source, /normalizeStatusSelects/);
assert.match(source, /reorderTableColumns/);
assert.match(source, /removeActionCells/);
assert.match(source, /setCompletedAtFromDuration/);
assert.match(markup, /editDurationValue/);
assert.match(fs.readFileSync('styles.css', 'utf8'), /#editDurationUnit/);
assert.match(source, /item\.type === 'project' && item\.status === 'done'/);
assert.match(fs.readFileSync('styles.css', 'utf8'), /\.table-scroll thead\{display:none\}/);
assert.match(fs.readFileSync('styles.css', 'utf8'), /td\.row-actions\{display:table-cell/);
assert.match(fs.readFileSync('styles.css', 'utf8'), /table-layout:fixed/);
assert.match(fs.readFileSync('styles.css', 'utf8'), /table-scroll table\{width:100%/);
assert.match(source, /writeWorkbookToHandle/);
assert.match(source, /Workbook kosong atau gagal dibuat/);
assert.match(source, /importReportMessage/);
assert.match(source, /async function parseWorkbook/);
assert.match(source, /skippedEmpty/);
assert.match(source, /recent-changes\.json/);
assert.match(source, /isSaving/);
assert.match(source, /normalizeWorkbookDateCells/);
assert.match(source, /Workbook kosong atau gagal dibuat/);
assert.match(source, /abort\(\)/);
assert.doesNotMatch(source, /writable\.write\(XLSX\.write/);

console.log('REQORD smoke checks passed');
