const assert = require('node:assert/strict');
const fs = require('node:fs');

const source = fs.readFileSync('app.js', 'utf8');
const markup = fs.readFileSync('index.html', 'utf8');

assert.match(source, /function normalizeStatus/);
assert.match(source, /function normalizePriority/);
assert.match(source, /function isDailyDone/);
assert.match(source, /function removeDefaultSheets/);
assert.match(source, /showSaveFilePicker/);
assert.match(source, /requestPermission/);
assert.match(source, /loadMoreDoneButton/);
assert.match(source, /priorityFilter/);
assert.match(source, /sortFilter/);
assert.match(markup, /daily-progress/);
assert.match(source, /hasUnsavedChanges/);
assert.match(source, /Perubahan belum disimpan akan diganti/);
assert.match(source, /downloadWorkbook/);
assert.match(source, /removeDefaultSheets/);
assert.match(source, /loadActivitiesFromFile/);
assert.match(source, /Details/);
assert.match(source, /Workbook di-load/);
assert.match(source, /Workbook disimpan/);
assert.doesNotMatch(source, /activities = activities\.slice\(0, 100\)/);
assert.match(markup, /activeFileName/);
assert.match(markup, /saveState/);
assert.match(source, /renderTitleSuggestions/);
assert.match(markup, /titleSuggestions/);
assert.match(markup, /estimateValue/);
assert.match(source, /estimateLabel/);
assert.match(fs.readFileSync('styles.css', 'utf8'), /\.table-scroll thead\{display:none\}/);
assert.match(fs.readFileSync('styles.css', 'utf8'), /td\.row-actions\{display:table-cell/);
assert.match(source, /writeWorkbookToHandle/);
assert.match(source, /Workbook kosong atau gagal dibuat/);
assert.match(source, /importReportMessage/);
assert.match(source, /async function parseWorkbook/);
assert.match(source, /skippedEmpty/);
assert.match(source, /recent-changes\.json/);
assert.match(source, /isSaving/);
assert.match(source, /normalizeWorkbookDateCells/);
assert.match(source, /Workbook kosong atau gagal dibuat/);
assert.match(source, /abort\(\)/);
assert.doesNotMatch(source, /writable\.write\(XLSX\.write/);

console.log('REQORD smoke checks passed');
