const STORAGE_KEY = 'reqord-request-work-orders';
const LEGACY_STORAGE_KEY = 'synaps-project-work-orders';
const groups = { list: 'Request list', ongoing: 'Ongoing request', done: 'Done request' };
const seedItems = [
  { id: 1, title: 'Update harga produk di website sebelum Jumat', requestor: 'Saya', type: 'project', status: 'list', priority: 'high', requestDate: '', date: '' },
  { id: 2, title: 'Buat laporan performa campaign bulan ini', requestor: 'Saya', type: 'project', status: 'list', priority: 'normal', requestDate: '', date: '' },
  { id: 3, title: 'Review proposal dari tim desain', requestor: 'AR', type: 'project', status: 'ongoing', priority: 'normal', requestDate: '', date: '' },
  { id: 4, title: 'Kirim invoice project September', requestor: 'Saya', type: 'project', status: 'done', priority: 'low', requestDate: '', date: '' }
];
let items = loadDraftItems();
let doneVisibleLimit = 10;
let openedFileHandle = null;
let openedFileName = '';
let hasUnsavedChanges = false;
let activities = [];
let storageDatabase = null;
let saveAsRequested = false;
const tableMap = { list: document.querySelector('#listTable'), ongoing: document.querySelector('#ongoingTable'), done: document.querySelector('#doneTable') };

function loadItems() { try { const current = JSON.parse(localStorage.getItem(STORAGE_KEY)); if (Array.isArray(current)) return current.map(normalizeItem); const legacy = JSON.parse(localStorage.getItem(LEGACY_STORAGE_KEY)); if (Array.isArray(legacy)) { const migrated = legacy.map(normalizeItem); localStorage.setItem(STORAGE_KEY, JSON.stringify(migrated)); return migrated; } return seedItems.map(normalizeItem); } catch { return seedItems.map(normalizeItem); } }
function saveItems() { hasUnsavedChanges = true; persistDraft(); return items; }
function loadDraftItems() { try { const current = JSON.parse(localStorage.getItem(STORAGE_KEY)); return Array.isArray(current) ? current.map(normalizeItem) : []; } catch { return []; } }
function persistDraft() { localStorage.setItem(STORAGE_KEY, JSON.stringify(items)); if (storageDatabase) { const transaction = storageDatabase.transaction('draft', 'readwrite'); transaction.objectStore('draft').put({ id: 'current', items, activities }); } }
function openDraftDatabase() { if (!window.indexedDB) return; const request = indexedDB.open('reqord-storage', 1); request.onupgradeneeded = () => request.result.createObjectStore('draft', { keyPath: 'id' }); request.onsuccess = () => { storageDatabase = request.result; const get = storageDatabase.transaction('draft', 'readonly').objectStore('draft').get('current'); get.onsuccess = () => { if (!get.result) return; activities = get.result.activities || activities; if (!items.length) items = (get.result.items || []).map(normalizeItem); renderActivities(); render(); }; }; }
function addActivity(action, item = {}) { activities.unshift({ date: nowDateTime(), action, title: item.title || '', requestor: item.requestor || '' }); activities = activities.slice(0, 100); persistDraft(); renderActivities(); }
function renderActivities() { const list = document.querySelector('#activityList'); if (!list) return; list.innerHTML = activities.length ? activities.map(activity => `<div class="activity-item"><strong>${escapeHtml(activity.action)}</strong><span>${escapeHtml(activity.title || 'REQORD')}</span><small>${escapeHtml(activity.date)}</small></div>`).join('') : '<p class="activity-empty">Belum ada activity.</p>'; }
function loadActivities(workbook) { const activitySheet = workbook.SheetNames.find(name => /^activity$/i.test(name)); activities = activitySheet ? XLSX.utils.sheet_to_json(workbook.Sheets[activitySheet]).map(row => ({ date: row.Date || '', action: row.Action || '', title: row.Title || '', requestor: row.Requestor || '' })).filter(activity => activity.action || activity.title).slice(-100).reverse() : []; renderActivities(); }
function escapeHtml(value) { return String(value).replace(/[&<>'"]/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char])); }
function normalizeItem(item) { return { ...item, requestor: String(item.requestor || item.owner || 'Tidak diketahui'), type: item.type === 'daily' || item.status === 'daily' ? 'daily' : 'project', status: normalizeStatus(item.status), priority: normalizePriority(item.priority), requestDate: normalizeDateValue(item.requestDate), date: normalizeDateValue(item.date || item.targetDone), done: Boolean(item.done), dailyDoneDate: item.dailyDoneDate || (item.done && item.type === 'daily' ? today() : '') }; }
function normalizeStatus(value) { const text = String(value || '').toLowerCase(); if (text.includes('daily')) return 'daily'; if (text.includes('ongoing') || text.includes('progress') || text.includes('kerja')) return 'ongoing'; if (text.includes('done') || text.includes('selesai') || text.includes('complete')) return 'done'; return 'list'; }
function normalizePriority(value) { const text = String(value || 'normal').toLowerCase(); return text.includes('high') || text.includes('penting') ? 'high' : text.includes('low') || text.includes('nanti') ? 'low' : 'normal'; }
function normalizeDateValue(value) { if (!value) return ''; if (value instanceof Date) return `${localDate(value)}T${String(value.getHours()).padStart(2, '0')}:${String(value.getMinutes()).padStart(2, '0')}`; if (typeof value === 'number' && window.XLSX?.SSF) { const parsed = XLSX.SSF.parse_date_code(value); if (parsed) return `${parsed.y}-${String(parsed.m).padStart(2, '0')}-${String(parsed.d).padStart(2, '0')}${parsed.H || parsed.M ? `T${String(parsed.H).padStart(2, '0')}:${String(parsed.M).padStart(2, '0')}` : ''}`; } return String(value).trim().replace(' ', 'T').slice(0, 16); }
function nowDateTime() { const date = new Date(); return `${localDate(date)}T${String(date.getHours()).padStart(2, '0')}:${String(date.getMinutes()).padStart(2, '0')}`; }
function today() { return localDate(new Date()); }
function isDailyDone(item) { return item.type === 'daily' && item.dailyDoneDate === today(); }
function refreshDailyDates() { items.filter(item => item.type === 'daily').forEach(item => { item.requestDate = today(); item.date = today(); item.done = isDailyDone(item); }); }
function localDate(date) { return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`; }
function dateAfterDays(days, base = today()) { const date = new Date(base.includes('T') ? base : `${base}T00:00:00`); date.setDate(date.getDate() + days); return localDate(date); }
function displayDate(value, includeTime = false) { if (!value) return 'No date'; const date = new Date(value.includes('T') ? value : `${value}T00:00:00`); if (Number.isNaN(date.getTime())) return value; return date.toLocaleDateString('id-ID', { day: 'numeric', month: 'short', ...(includeTime ? { year: 'numeric' } : {}) }) + (includeTime && value.includes('T') ? `, ${date.toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' })}` : ''); }
function targetDoneLabel(value) { if (!value) return '<span class="target-empty">No target</span>'; const target = new Date(`${value}T00:00:00`); const current = new Date(`${today()}T00:00:00`); if (Number.isNaN(target.getTime())) return escapeHtml(value); const days = Math.ceil((target - current) / 86400000); const date = target.toLocaleDateString('id-ID', { day: 'numeric', month: 'short', year: 'numeric' }); const detail = days < 0 ? `Terlambat ${Math.abs(days)} hari` : days === 0 ? 'Hari ini' : days === 1 ? 'Besok' : `${days} hari lagi`; return `<span class="target-date">${escapeHtml(date)}</span><small class="target-detail">${detail}</small>`; }
function urgencyClass(deadline) { if (!deadline) return ''; const daysLeft = Math.ceil((new Date(`${deadline}T00:00:00`) - new Date(`${today()}T00:00:00`)) / 86400000); return daysLeft <= 1 ? 'deadline-red' : daysLeft === 2 ? 'deadline-yellow' : ''; }
function requestors() { return [...new Set(items.map(item => item.requestor).filter(Boolean))]; }
function similarityScore(query, name) { if (!query) return 1; if (name === query) return 100; if (name.includes(query)) return 80 - name.indexOf(query); if (query.length < 3) return 0; const matches = [...query].filter(character => name.includes(character)).length; return matches / query.length >= .7 ? 40 - (name.length - query.length) : 0; }
let requestorMatches = [];
let requestorActiveIndex = -1;
function initials(name) { return String(name).split(/\s+/).filter(Boolean).slice(0, 2).map(part => part[0]).join('').toUpperCase(); }
function renderRequestorSuggestions() { const input = document.querySelector('#requestorInput'); const suggestions = document.querySelector('#requestorSuggestions'); const query = input.value.trim().toLowerCase(); if (!query && document.activeElement !== input) { closeRequestorSuggestions(); return; } requestorMatches = requestors().map(name => ({ name, score: similarityScore(query, name.toLowerCase()) })).filter(item => !query || item.score > 0).sort((a, b) => b.score - a.score).slice(0, 6).map(item => item.name); requestorActiveIndex = -1; suggestions.innerHTML = requestorMatches.length ? `<div class="suggestion-heading">${query ? 'Matching requestors' : 'Recent requestors'}<span>${requestorMatches.length}</span></div>${requestorMatches.map((name, index) => `<button type="button" role="option" aria-selected="false" data-index="${index}" data-requestor="${escapeHtml(name)}"><span class="suggestion-avatar">${escapeHtml(initials(name))}</span><span class="suggestion-name">${escapeHtml(name)}</span><span class="suggestion-arrow">↵</span></button>`).join('')}` : `<div class="suggestion-empty">Belum ada requestor yang cocok</div>`; suggestions.hidden = !requestorMatches.length; input.setAttribute('aria-expanded', String(requestorMatches.length > 0)); }
function closeRequestorSuggestions() { const suggestions = document.querySelector('#requestorSuggestions'); const input = document.querySelector('#requestorInput'); suggestions.hidden = true; input.setAttribute('aria-expanded', 'false'); requestorActiveIndex = -1; }
function chooseRequestor(name) { document.querySelector('#requestorInput').value = name; closeRequestorSuggestions(); }
function render() { const query = document.querySelector('#searchInput').value.trim().toLowerCase(); if (query) doneVisibleLimit = 10; const visible = items.filter(item => !query || `${item.title} ${item.requestor}`.toLowerCase().includes(query)); Object.keys(tableMap).forEach(status => { const allRows = visible.filter(item => item.type === 'project' && item.status === status); const rows = status === 'done' ? allRows.slice(0, doneVisibleLimit) : allRows; tableMap[status].innerHTML = rows.map(renderRow).join(''); document.querySelector(`#${status}Count`).textContent = items.filter(item => item.type === 'project' && item.status === status).length; document.querySelector(`#${status}Empty`).hidden = rows.length !== 0; if (status === 'done') { const loadMoreButton = document.querySelector('#loadMoreDoneButton'); loadMoreButton.hidden = allRows.length <= 10 || rows.length >= allRows.length; loadMoreButton.textContent = `Load more done works (${Math.min(doneVisibleLimit + 10, allRows.length)}/${allRows.length})`; } }); renderDailyTasks(visible.filter(item => item.type === 'daily')); document.querySelector('#resultCount').textContent = `${visible.length} of ${items.length} work orders`; renderRequestorSuggestions(); }
function renderRow(item) { const takeButton = item.status === 'list' ? `<button class="action-button take-action" data-row-action="take" data-id="${item.id}" title="Saya mau kerjain" aria-label="Saya mau kerjain">▶</button>` : ''; const completeButton = item.status === 'done' ? '' : `<button class="action-button complete-action" data-row-action="complete" data-id="${item.id}" title="Tandai selesai" aria-label="Tandai selesai">✓</button>`; const revisionButton = item.status === 'done' ? `<button class="action-button revision-action" data-row-action="revision" data-id="${item.id}" title="Kembalikan untuk revisi" aria-label="Kembalikan untuk revisi">↻</button>` : ''; return `<tr class="${urgencyClass(item.date)}"><td class="title-cell">${escapeHtml(item.title)}</td><td>${escapeHtml(item.requestor)}</td><td><select class="status-select status-${item.status}" data-action="status" data-id="${item.id}" aria-label="Status"><option value="list" ${item.status === 'list' ? 'selected' : ''}>Request list</option><option value="ongoing" ${item.status === 'ongoing' ? 'selected' : ''}>Ongoing request</option><option value="done" ${item.status === 'done' ? 'selected' : ''}>Done request</option><option value="daily" ${item.type === 'daily' ? 'selected' : ''}>Daily task</option></select></td><td><select class="priority-select priority-${item.priority}" data-action="priority" data-id="${item.id}" aria-label="Priority"><option value="high" ${item.priority === 'high' ? 'selected' : ''}>High</option><option value="normal" ${item.priority === 'normal' ? 'selected' : ''}>Normal</option><option value="low" ${item.priority === 'low' ? 'selected' : ''}>Low</option></select></td><td>${escapeHtml(displayDate(item.requestDate, true))}</td><td class="target-cell" title="Target done: ${escapeHtml(displayDate(item.date, true))}">${targetDoneLabel(item.date)}</td><td class="row-actions">${takeButton}${completeButton}${revisionButton}<button class="action-button delete-action" data-row-action="delete" data-id="${item.id}" title="Hapus request" aria-label="Hapus request">⌫</button></td></tr>`; }
function renderDailyTasks(tasks) { refreshDailyDates(); document.querySelector('#dailyCount').textContent = items.filter(item => item.type === 'daily').length; document.querySelector('#dailyTable').innerHTML = tasks.map(renderDailyRow).join(''); document.querySelector('#dailyEmpty').hidden = tasks.length !== 0; }
function renderDailyRow(item) { const doneToday = isDailyDone(item); const completeButton = `<button class="action-button complete-action daily-check ${doneToday ? 'daily-done' : ''}" data-row-action="daily-done" data-id="${item.id}" title="${doneToday ? 'Selesai hari ini, klik untuk batalkan' : 'Tandai selesai hari ini'}" aria-label="${doneToday ? 'Selesai hari ini, klik untuk batalkan' : 'Tandai selesai hari ini'}" aria-pressed="${doneToday}">${doneToday ? '☑' : '☐'}</button>`; return `<tr class="${doneToday ? 'daily-row-done' : urgencyClass(item.date)}"><td class="title-cell ${doneToday ? 'daily-title-done' : ''}">${escapeHtml(item.title)}</td><td>${escapeHtml(item.requestor)}</td><td><select class="status-select status-daily" data-action="status" data-id="${item.id}" aria-label="Status"><option value="daily" selected>Daily task</option><option value="list">Request list</option><option value="ongoing">Ongoing request</option><option value="done">Done request</option></select></td><td><select class="priority-select priority-${item.priority}" data-action="priority" data-id="${item.id}" aria-label="Priority"><option value="high" ${item.priority === 'high' ? 'selected' : ''}>High</option><option value="normal" ${item.priority === 'normal' ? 'selected' : ''}>Normal</option><option value="low" ${item.priority === 'low' ? 'selected' : ''}>Low</option></select></td><td>${escapeHtml(displayDate(item.requestDate, false))}</td><td class="target-cell" title="Done today: ${escapeHtml(displayDate(item.date, false))}">${escapeHtml(displayDate(item.date, false))}</td><td class="row-actions">${completeButton}<button class="action-button delete-action" data-row-action="delete" data-id="${item.id}" title="Hapus daily task" aria-label="Hapus daily task">⌫</button></td></tr>`; }
function showToast(message) { const toast = document.querySelector('#toast'); toast.textContent = message; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 2400); }
function findItem(id) { return items.find(item => String(item.id) === String(id)); }

document.querySelector('#workOrderForm').addEventListener('submit', event => { event.preventDefault(); const form = new FormData(event.currentTarget); const title = String(form.get('title')).trim(); const requestor = String(form.get('requestor')).trim(); if (!title || !requestor) { document.querySelector('#requestorInput').focus(); showToast('Requestor wajib diisi'); return; } const requestDate = form.get('requestDate') || nowDateTime(); const targetDone = dateAfterDays(3, requestDate); const item = { id: Date.now(), title, requestor, type: 'project', status: 'list', priority: form.get('priority'), requestDate, date: targetDone, done: false }; items.unshift(item); saveItems(); addActivity('Work order ditambahkan', item); render(); event.currentTarget.reset(); setFormDates(); showToast(`Request masuk ke Request list · target done ${displayDate(targetDone)}`); });
document.querySelector('#searchInput').addEventListener('input', render);
document.querySelector('#loadMoreDoneButton').addEventListener('click', () => { doneVisibleLimit += 10; render(); });
document.querySelector('#newButton').addEventListener('click', () => { if (hasUnsavedChanges && !window.confirm('Perubahan belum disimpan. Buat draft baru?')) return; items = []; activities = []; openedFileHandle = null; openedFileName = ''; hasUnsavedChanges = false; persistDraft(); renderActivities(); render(); showToast('Draft baru dibuat'); });
document.querySelector('#saveAsButton').addEventListener('click', () => { saveAsRequested = true; document.querySelector('#exportButton').click(); });
document.querySelector('#refreshButton').addEventListener('click', async () => { if (!openedFileHandle) { render(); showToast('Belum ada workbook yang di-load'); return; } if (hasUnsavedChanges && !window.confirm('Perubahan belum disimpan akan ditimpa. Refresh workbook?')) return; try { await loadWorkbook(await openedFileHandle.getFile()); hasUnsavedChanges = false; showToast(`${openedFileName} berhasil di-refresh`); } catch { showToast('Refresh workbook gagal'); } });
document.querySelector('#requestorInput').addEventListener('input', renderRequestorSuggestions); document.querySelector('#requestorInput').addEventListener('focus', renderRequestorSuggestions); document.querySelector('#requestorInput').addEventListener('keydown', event => { if (!requestorMatches.length) return; if (event.key === 'ArrowDown' || event.key === 'ArrowUp') { event.preventDefault(); requestorActiveIndex = (requestorActiveIndex + (event.key === 'ArrowDown' ? 1 : requestorMatches.length - 1)) % requestorMatches.length; document.querySelectorAll('#requestorSuggestions [data-requestor]').forEach((button, index) => button.classList.toggle('active', index === requestorActiveIndex)); } if (event.key === 'Enter' && requestorActiveIndex >= 0) { event.preventDefault(); chooseRequestor(requestorMatches[requestorActiveIndex]); } if (event.key === 'Escape') closeRequestorSuggestions(); }); document.querySelector('#requestorSuggestions').addEventListener('pointerdown', event => { const button = event.target.closest('[data-requestor]'); if (!button) return; event.preventDefault(); event.stopPropagation(); chooseRequestor(button.dataset.requestor); }); document.addEventListener('click', event => { if (!event.target.closest('.requestor-field')) closeRequestorSuggestions(); });
document.addEventListener('keydown', event => { if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === 'k') { event.preventDefault(); document.querySelector('#titleInput').focus(); } if (event.key === 'Escape') closeRequestorSuggestions(); });
const profileDialog = document.querySelector('#profileDialog');
document.querySelector('#profileButton').addEventListener('click', () => profileDialog.showModal());
document.querySelector('#closeProfileButton').addEventListener('click', () => profileDialog.close());
profileDialog.addEventListener('click', event => { if (event.target === profileDialog) profileDialog.close(); });
const activityPanel = document.querySelector('#activityPanel');
document.querySelector('#activityButton').addEventListener('click', () => { activityPanel.classList.add('open'); activityPanel.setAttribute('aria-hidden', 'false'); });
document.querySelector('#closeActivityButton').addEventListener('click', () => { activityPanel.classList.remove('open'); activityPanel.setAttribute('aria-hidden', 'true'); });
function downloadTemplate() { if (!window.XLSX) { showToast('Library XLSX belum tersedia'); return; } const workbook = XLSX.utils.book_new(); const requestHeaders = ['Title', 'Requestor', 'Status', 'Priority', 'RequestDate', 'TargetDone']; const sheets = { 'Request List': requestHeaders, 'Ongoing Requests': requestHeaders, 'Done Requests': requestHeaders, 'Daily Tasks': ['Task', 'Requestor', 'Date', 'Priority', 'Done'] }; Object.entries(sheets).forEach(([name, headers]) => { const sheet = XLSX.utils.aoa_to_sheet([headers, headers[0] === 'Title' ? ['Contoh work order (hapus baris ini)', '', 'Request list', 'Normal', '', ''] : ['Contoh daily task (hapus baris ini)', '', '', 'Normal', 'No']]); sheet['!autofilter'] = { ref: `A1:${String.fromCharCode(64 + headers.length)}1` }; sheet['!cols'] = headers.map(header => ({ wch: header === 'Title' || header === 'Task' ? 42 : header === 'Requestor' ? 22 : 16 })); XLSX.utils.book_append_sheet(workbook, sheet, name); }); const readMe = XLSX.utils.aoa_to_sheet([['REQORD WORK ORDER TEMPLATE'], ['Isi data di sheet yang sesuai, hapus baris contoh, lalu buka file ini melalui Open file di REQORD.'], [''], ['Sheet', 'Keterangan'], ['Request List', 'Request baru yang belum dikerjakan'], ['Ongoing Requests', 'Request yang sedang dikerjakan'], ['Done Requests', 'Request yang sudah selesai'], ['Daily Tasks', 'Pekerjaan rutin; Done diisi Yes atau No'], [''], ['Kolom request', 'Title, Requestor, Status, Priority, RequestDate, TargetDone'], ['Kolom daily task', 'Task, Requestor, Date, Priority, Done']]); readMe['!cols'] = [{ wch: 24 }, { wch: 78 }]; XLSX.utils.book_append_sheet(workbook, readMe, 'Read me'); const file = XLSX.write(workbook, { bookType: 'xlsx', type: 'array' }); const url = URL.createObjectURL(new Blob([file], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' })); const link = document.createElement('a'); link.href = url; link.download = 'REQORD-table-template.xlsx'; link.click(); URL.revokeObjectURL(url); showToast('Template table berhasil diunduh'); }
document.querySelector('#templateButton').addEventListener('click', downloadTemplate);
document.querySelectorAll('[data-profile-view]').forEach(button => button.addEventListener('click', () => showToast(`${button.dataset.profileView === 'changelog' ? 'Changelog' : 'History'} akan tersedia di panel berikutnya`)));
document.querySelector('.table-stack').addEventListener('change', event => { const control = event.target; const item = findItem(control.dataset.id); if (!item) return; if (control.dataset.action === 'status') { item.status = control.value; item.type = control.value === 'daily' ? 'daily' : 'project'; if (control.value === 'done') item.done = true; } else if (control.dataset.action === 'priority') item.priority = control.value; else return; saveItems(); addActivity(control.dataset.action === 'priority' ? 'Priority diubah' : `Status menjadi ${item.status}`, item); render(); showToast(item.type === 'daily' ? 'Dipindahkan ke Daily tasks' : item.status === 'done' ? 'Request selesai' : 'Request diperbarui'); });
let deleteTargetId = null;
const deleteDialog = document.querySelector('#deleteDialog');
const deleteConfirmInput = document.querySelector('#deleteConfirmInput');
const confirmDeleteButton = document.querySelector('#confirmDeleteButton');
function openDeleteDialog(id) { deleteTargetId = id; deleteConfirmInput.value = ''; confirmDeleteButton.disabled = true; deleteDialog.showModal(); setTimeout(() => deleteConfirmInput.focus(), 0); }
function closeDeleteDialog() { deleteTargetId = null; deleteDialog.close(); }
document.querySelector('.table-stack').addEventListener('click', event => { const button = event.target.closest('[data-row-action]'); if (!button) return; const item = findItem(button.dataset.id); if (!item) return; if (button.dataset.rowAction === 'daily-done') { item.dailyDoneDate = isDailyDone(item) ? '' : today(); saveItems(); addActivity(item.dailyDoneDate ? 'Daily task selesai hari ini' : 'Daily task dibuka lagi', item); render(); showToast(item.dailyDoneDate ? 'Daily task selesai hari ini' : 'Daily task dibuka lagi'); return; } if (button.dataset.rowAction === 'take') { item.status = 'ongoing'; item.type = 'project'; item.done = false; saveItems(); addActivity('Request mulai dikerjakan', item); render(); showToast('Saya kerjain request ini'); return; } if (button.dataset.rowAction === 'complete') { item.status = 'done'; item.type = 'project'; item.done = true; saveItems(); addActivity('Request selesai', item); render(); showToast('Request ditandai selesai'); return; } if (button.dataset.rowAction === 'revision') { item.status = 'ongoing'; item.type = 'project'; item.done = false; saveItems(); addActivity('Request dikembalikan untuk revisi', item); render(); showToast('Request dikembalikan untuk revisi'); return; } if (button.dataset.rowAction === 'delete') openDeleteDialog(item.id); });
deleteConfirmInput.addEventListener('input', () => { confirmDeleteButton.disabled = deleteConfirmInput.value.trim().toLowerCase() !== 'saya sudah pikirin'; });
confirmDeleteButton.addEventListener('click', () => { if (confirmDeleteButton.disabled || deleteTargetId === null) return; const item = findItem(deleteTargetId); items = items.filter(item => item.id !== deleteTargetId); saveItems(); addActivity('Request dihapus', item); closeDeleteDialog(); render(); showToast('Request dihapus permanen'); });
document.querySelector('#closeDeleteButton').addEventListener('click', closeDeleteDialog); document.querySelector('#cancelDeleteButton').addEventListener('click', closeDeleteDialog); deleteDialog.addEventListener('click', event => { if (event.target === deleteDialog) closeDeleteDialog(); });
async function loadWorkbook(file) { if (!window.XLSX) throw new Error('XLSX unavailable'); const workbook = XLSX.read(await file.arrayBuffer(), { type: 'array' }); const sourceSheets = workbook.SheetNames.filter(name => /request list|ongoing requests|done requests|project list|ongoing projects|done projects/i.test(name)); const dailySheet = workbook.SheetNames.find(name => /daily tasks/i.test(name)); const rows = (sourceSheets.length ? sourceSheets : workbook.SheetNames.slice(0, 1)).flatMap(sheetName => XLSX.utils.sheet_to_json(workbook.Sheets[sheetName]).map(row => ({ ...row, __sheetStatus: sheetName }))); const imported = rows.map((row, index) => { const requestDate = normalizeDateValue(row.RequestDate || row.requestDate) || today(); const sheetStatus = /ongoing/i.test(row.__sheetStatus) ? 'ongoing' : /done/i.test(row.__sheetStatus) ? 'done' : 'list'; return normalizeItem({ id: Date.now() + index, title: row.Title || row.title || row.Name || `Imported request ${index + 1}`, requestor: row.Requestor || row.requestor || row.Owner || row.owner, type: 'project', status: row.Status ? normalizeStatus(row.Status) : sheetStatus, priority: normalizePriority(row.Priority), requestDate, date: normalizeDateValue(row.TargetDone || row.targetDone || row.Deadline || row.deadline) || dateAfterDays(3, requestDate) }); }); if (dailySheet) { const dailyRows = XLSX.utils.sheet_to_json(workbook.Sheets[dailySheet]); dailyRows.forEach((row, index) => imported.push(normalizeItem({ id: Date.now() + imported.length + index, title: row.Task || row.Title, requestor: row.Requestor, type: 'daily', status: 'daily', priority: normalizePriority(row.Priority), requestDate: normalizeDateValue(row.Date || row.RequestDate) || today(), date: dateAfterDays(3, normalizeDateValue(row.Date || row.RequestDate) || today()), done: String(row.Done || '').toLowerCase() === 'yes' || String(row.Done || '').toLowerCase() === 'true' }))); } if (!imported.length) throw new Error('empty'); items = imported; saveItems(); render(); document.querySelector('#exportButton').disabled = false; document.querySelector('#exportButton').title = `Save changes to ${openedFileName || 'this file'}`; showToast(`${imported.length} item loaded`); }
document.querySelector('#importButton').addEventListener('click', async () => { try { if (window.showOpenFilePicker) { [openedFileHandle] = await window.showOpenFilePicker({ types: [{ description: 'Excel workbook', accept: { 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet': ['.xlsx'] } }], multiple: false }); const file = await openedFileHandle.getFile(); openedFileName = file.name; await loadActivitiesFromFile(file); await loadWorkbook(file); hasUnsavedChanges = false; } else document.querySelector('#fileInput').click(); } catch (error) { if (error.name !== 'AbortError') showToast('Open file gagal'); } });
document.querySelector('#fileInput').addEventListener('change', async event => { const file = event.target.files[0]; if (!file) return; openedFileHandle = null; openedFileName = file.name; try { await loadActivitiesFromFile(file); await loadWorkbook(file); hasUnsavedChanges = false; } catch { showToast('Open file gagal. Periksa sheet request/Daily Tasks dan header kolomnya.'); } event.target.value = ''; });
document.querySelector('#exportButton').addEventListener('click', () => { if (!window.XLSX) { showToast('Library XLSX belum tersedia'); return; } const rows = items.filter(item => item.type === 'project').map(item => ({ Title: item.title, Requestor: item.requestor, Status: groups[item.status], Priority: item.priority, RequestDate: item.requestDate || '', TargetDone: item.date })); const workbook = XLSX.utils.book_new(); const readMe = [['REQORD WORK ORDER FILE'], ['Edit file ini di Excel, lalu buka kembali dengan Open file di REQORD.'], [''], ['Kolom', 'Keterangan'], ['Title', 'Judul request atau daily task'], ['Requestor', 'Nama pengaju'], ['Status', 'Request list, Ongoing request, atau Done request'], ['Priority', 'High, Normal, atau Low'], ['RequestDate', 'Tanggal dan jam dibuat'], ['TargetDone', 'Target selesai otomatis tiga hari setelah RequestDate'], ['Daily Tasks', 'Task rutin; gunakan kolom Done bernilai Yes atau No']]; const sheets = { 'Request List': 'list', 'Ongoing Requests': 'ongoing', 'Done Requests': 'done' }; Object.entries(sheets).forEach(([sheetName, status]) => { const sheetRows = rows.filter(row => row.Status === groups[status]); const sheet = XLSX.utils.json_to_sheet(sheetRows, { header: ['Title', 'Requestor', 'Status', 'Priority', 'RequestDate', 'TargetDone'] }); sheet['!autofilter'] = { ref: `A1:F${Math.max(sheetRows.length + 1, 1)}` }; sheet['!cols'] = [{ wch: 48 }, { wch: 22 }, { wch: 20 }, { wch: 12 }, { wch: 22 }, { wch: 16 }]; XLSX.utils.book_append_sheet(workbook, sheet, sheetName); }); const dailyRows = items.filter(item => item.type === 'daily').map(task => ({ Task: task.title, Requestor: task.requestor, Date: task.requestDate, Priority: task.priority, Done: task.done ? 'Yes' : 'No' })); const dailySheet = XLSX.utils.json_to_sheet(dailyRows, { header: ['Task', 'Requestor', 'Date', 'Priority', 'Done'] }); dailySheet['!autofilter'] = { ref: `A1:E${Math.max(dailyRows.length + 1, 1)}` }; dailySheet['!cols'] = [{ wch: 48 }, { wch: 22 }, { wch: 22 }, { wch: 12 }, { wch: 10 }]; XLSX.utils.book_append_sheet(workbook, dailySheet, 'Daily Tasks'); XLSX.utils.book_append_sheet(workbook, XLSX.utils.aoa_to_sheet(readMe), 'Read me'); XLSX.writeFile(workbook, `reqord-work-orders-${new Date().toISOString().slice(0, 10)}.xlsx`); showToast(`${items.length} item disimpan ke Excel`); });
window.addEventListener('beforeunload', event => { if (!hasUnsavedChanges) return; event.preventDefault(); event.returnValue = 'Perubahan belum disimpan. Simpan dulu sebelum keluar?'; });
function addActivitySheet(workbook) { const rows = activities.map(activity => ({ Date: activity.date, Action: activity.action, Title: activity.title, Requestor: activity.requestor })); const sheet = XLSX.utils.json_to_sheet(rows, { header: ['Date', 'Action', 'Title', 'Requestor'] }); sheet['!autofilter'] = { ref: `A1:D${Math.max(rows.length + 1, 1)}` }; sheet['!cols'] = [{ wch: 20 }, { wch: 32 }, { wch: 48 }, { wch: 22 }]; if (workbook.SheetNames.includes('Activity')) workbook.Sheets.Activity = sheet; else XLSX.utils.book_append_sheet(workbook, sheet, 'Activity'); }
const originalWriteFile = window.XLSX?.writeFile;
if (originalWriteFile) window.XLSX.writeFile = async workbook => { try { addActivitySheet(workbook); if ((saveAsRequested || !openedFileHandle) && window.showSaveFilePicker) { [openedFileHandle] = await window.showSaveFilePicker({ suggestedName: saveAsRequested ? 'REQORD-work-orders.xlsx' : (openedFileName || 'REQORD-work-orders.xlsx'), types: [{ description: 'Excel workbook', accept: { 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet': ['.xlsx'] } }] }); openedFileName = openedFileHandle.name; } if (!openedFileHandle) { originalWriteFile(workbook, `REQORD-${openedFileName || 'work-orders'}`); hasUnsavedChanges = false; saveAsRequested = false; showToast('Draft berhasil diunduh sebagai file Excel baru'); return; } const writable = await openedFileHandle.createWritable(); await writable.write(XLSX.write(workbook, { bookType: 'xlsx', type: 'array' })); await writable.close(); hasUnsavedChanges = false; saveAsRequested = false; persistDraft(); showToast(`${openedFileName} berhasil disimpan`); } catch (error) { saveAsRequested = false; if (error.name !== 'AbortError') showToast('Save gagal. Pilih file Excel atau berikan izin tulis.'); } };
function setFormDates() { document.querySelector('#requestDateInput').value = nowDateTime(); }
setFormDates(); openDraftDatabase(); renderActivities(); render();
