const STORAGE_KEY = 'reqord-request-work-orders';
const LEGACY_STORAGE_KEY = 'synaps-project-work-orders';
const groups = { list: 'Request list', ongoing: 'Ongoing request', revision: 'On revision', preview: 'Preview', done: 'Done request' };
const seedItems = [
  { id: 1, title: 'Update harga produk di website sebelum Jumat', requestor: 'Saya', type: 'project', status: 'list', priority: 'high', requestDate: '', date: '' },
  { id: 2, title: 'Buat laporan performa campaign bulan ini', requestor: 'Saya', type: 'project', status: 'list', priority: 'normal', requestDate: '', date: '' },
  { id: 3, title: 'Review proposal dari tim desain', requestor: 'AR', type: 'project', status: 'ongoing', priority: 'normal', requestDate: '', date: '' },
  { id: 4, title: 'Kirim invoice project September', requestor: 'Saya', type: 'project', status: 'done', priority: 'low', requestDate: '', date: '' }
];
localStorage.removeItem(STORAGE_KEY);
let items = [];
let doneVisibleLimit = 10;
let openedFileHandle = null;
let openedFileName = '';
let hasUnsavedChanges = false;
let activities = [];
let storageDatabase = null;
let isLoadingWorkbook = false;
let isSaving = false;
const saveAsRequested = false;
let lastImportReport = { loaded: 0, skippedEmpty: 0, skippedInvalid: 0 };
let deletedItem = null;
let priorityFilter = 'all';
let sortFilter = 'newest';
const tableMap = { list: document.querySelector('#listTable'), ongoing: document.querySelector('#ongoingTable'), revision: document.querySelector('#revisionTable'), preview: document.querySelector('#previewTable'), done: document.querySelector('#doneTable') };

function loadItems() { try { const current = JSON.parse(localStorage.getItem(STORAGE_KEY)); if (Array.isArray(current)) return current.map(normalizeItem); const legacy = JSON.parse(localStorage.getItem(LEGACY_STORAGE_KEY)); if (Array.isArray(legacy)) { const migrated = legacy.map(normalizeItem); localStorage.setItem(STORAGE_KEY, JSON.stringify(migrated)); return migrated; } return seedItems.map(normalizeItem); } catch { return seedItems.map(normalizeItem); } }
function saveItems() { if (!isLoadingWorkbook) hasUnsavedChanges = true; persistDraft(); return items; }
function loadDraftItems() { try { const current = JSON.parse(localStorage.getItem(STORAGE_KEY)); return Array.isArray(current) ? current.map(normalizeItem) : []; } catch { return []; } }
function persistDraft() { try { localStorage.setItem(STORAGE_KEY, JSON.stringify(items)); if (storageDatabase) { const transaction = storageDatabase.transaction('draft', 'readwrite'); transaction.objectStore('draft').put({ id: 'current', items, activities }); } } catch { showToast('Draft lokal tidak bisa disimpan di browser ini'); } }
function openDraftDatabase() { if (!window.indexedDB) return; const request = indexedDB.open('reqord-storage', 1); request.onupgradeneeded = () => request.result.createObjectStore('draft', { keyPath: 'id' }); request.onsuccess = () => { storageDatabase = request.result; const clear = storageDatabase.transaction('draft', 'readwrite').objectStore('draft').clear(); clear.onsuccess = () => { items = []; activities = []; renderActivities(); render(); }; }; }
function addActivity(action, item = {}, details = '') { activities.unshift({ date: nowDateTime(), action, title: item.title || '', requestor: item.requestor || '', details }); persistDraft(); renderActivities(); }
function renderActivities() { const list = document.querySelector('#activityList'); if (!list) return; list.innerHTML = activities.length ? activities.map(activity => `<div class="activity-item"><strong>${escapeHtml(activity.action)}</strong><span>${escapeHtml(activity.title || activity.details || 'REQORD')}</span><small>${escapeHtml(displayDate(activity.date, true))}${activity.requestor ? ` · ${escapeHtml(activity.requestor)}` : ''}</small></div>`).join('') : '<p class="activity-empty">Belum ada activity.</p>'; }
function centerActionGroups() { document.querySelectorAll('.table-scroll td.row-actions').forEach(cell => { let group = cell.querySelector('.actions-inner'); if (!group) { group = document.createElement('div'); group.className = 'actions-inner'; while (cell.firstChild) group.append(cell.firstChild); cell.append(group); } const count = group.querySelectorAll('.action-button').length; group.dataset.count = String(count); group.style.setProperty('--action-count', Math.min(count, 3)); group.className = `actions-inner actions-count-${count}`; }); }
function enhanceDurationCells() { document.querySelectorAll('.duration-cell').forEach(cell => { if (cell.querySelector('.duration-edit-button')) return; const row = cell.closest('tr'); const control = row?.querySelector('[data-id]'); const item = control && findItem(control.dataset.id); if (!item) return; cell.innerHTML = `<span>${escapeHtml(completionDuration(item))}</span><button class="duration-edit-button" data-duration-edit-id="${item.id}" type="button" title="Edit waktu pengerjaan" aria-label="Edit waktu pengerjaan">✎</button>`; }); }
function renderSubitemCells() { document.querySelectorAll('.table-scroll tbody tr').forEach(row => { const control = row.querySelector('[data-id]'); const item = control && findItem(control.dataset.id); const title = row.querySelector('.title-cell'); if (!item || !title) return; item.subitems = Array.isArray(item.subitems) ? item.subitems : []; let badge = title.querySelector('.subitem-count'); if (!badge) { badge = document.createElement('small'); badge.className = 'subitem-count'; title.append(' ', badge); } const count = item.subitems.length; const done = item.subitems.filter(subitem => subitem.done).length; badge.textContent = count ? `${done}/${count} subitems` : 'Subitems'; title.classList.add('has-subitems'); title.tabIndex = 0; title.dataset.subitemId = item.id; title.setAttribute('role', 'button'); }); }
function normalizeDailyProgressCells() { document.querySelectorAll('#dailyTable tr').forEach(row => { const item = findItem(row.querySelector('[data-id]')?.dataset.id); const title = row.querySelector('.title-cell'); const requestor = row.querySelector('td:nth-child(2)'); const status = row.querySelector('.status-select')?.closest('td'); const priority = row.querySelector('.priority-select')?.closest('td'); if (!item || !title || !requestor || !status || !priority) return; [...row.children].forEach(cell => { if (![title, requestor, status, priority].includes(cell)) cell.remove(); }); const progress = document.createElement('td'); progress.className = 'daily-progress-cell-wrap'; const done = isDailyDone(item); progress.innerHTML = `<span class="daily-progress-cell"><small>${escapeHtml(displayDate(today(), false))}</small><button class="action-button complete-action daily-check ${done ? 'daily-done' : ''}" data-row-action="daily-done" data-id="${item.id}" title="${done ? 'Selesai, klik untuk batalkan' : 'Tandai selesai'}" aria-label="${done ? 'Selesai, klik untuk batalkan' : 'Tandai selesai'}" aria-pressed="${done}">${done ? '☑' : '☐'}</button></span>`; priority.after(progress); }); }
function renderInlineSubitems() { document.querySelectorAll('.subitem-inline').forEach(row => row.remove()); Object.entries(tableMap).forEach(([status, tableBody]) => { if (!tableBody) return; tableBody.querySelectorAll('tr:not(.subitem-inline)').forEach(row => { const control = row.querySelector('[data-id]'); const item = control && findItem(control.dataset.id); if (!item || item.type !== 'project' || item.status !== status) return; item.subitems = Array.isArray(item.subitems) ? item.subitems : []; if (!item.subitems.length) return; const table = row.closest('table'); const inlineRow = document.createElement('tr'); inlineRow.className = 'subitem-inline'; inlineRow.dataset.parentId = item.id; const cell = document.createElement('td'); cell.colSpan = table?.tHead?.rows[0]?.cells.length || 6; cell.innerHTML = `<div class="subitem-inline-list">${item.subitems.map(subitem => `<label class="subitem-inline-item"><input type="checkbox" data-inline-subitem-parent="${item.id}" data-inline-subitem-id="${subitem.id}" ${subitem.done ? 'checked' : ''}><span>${escapeHtml(subitem.title)}</span></label>`).join('')}</div>`; inlineRow.append(cell); row.after(inlineRow); }); }); }
function removeActionCells() { document.querySelectorAll('.table-scroll tbody tr .row-actions').forEach(actions => actions.remove()); }
function normalizeStatusSelects() { document.querySelectorAll('.status-select').forEach(select => { const item = findItem(select.dataset.id); const current = item?.status || select.value; select.innerHTML = '<option value="list">Request list</option><option value="ongoing">Ongoing request</option><option value="preview">Preview</option><option value="revision">On revision</option><option value="done">Done request</option><option value="daily">Daily tasks</option>'; select.value = current; }); }
function reorderTableColumns() { document.querySelectorAll('.table-scroll tbody tr').forEach(row => { const cells = row.children; if (cells.length > 4) row.insertBefore(cells[4], cells[3]); }); }
function makeRowsEditable() { document.querySelectorAll('.table-scroll tbody tr').forEach(row => { const control = row.querySelector('[data-id]'); if (!control) return; const id = control.dataset.id; const item = findItem(id); const title = row.querySelector('.title-cell'); const requestor = row.querySelector('td:nth-child(2)'); if (title) { title.removeAttribute('contenteditable'); title.removeAttribute('data-action'); title.removeAttribute('data-id'); title.classList.add('has-subitems'); title.dataset.subitemId = id; title.tabIndex = 0; title.setAttribute('role', 'button'); title.setAttribute('aria-label', `Tambah subitem untuk ${item?.title || 'work order'}`); } if (requestor) { requestor.removeAttribute('contenteditable'); requestor.removeAttribute('data-action'); requestor.removeAttribute('data-id'); } const actions = row.querySelector('.row-actions'); const status = row.querySelector('.status-select')?.value; if (actions && !actions.querySelector('[data-row-action="edit"]')) actions.insertAdjacentHTML('afterbegin', `<button class="action-button edit-action" data-row-action="edit" data-id="${id}" title="Edit work order" aria-label="Edit work order">✎</button>`); if (actions && status === 'done') { if (!actions.querySelector('[data-row-action="revision"]')) actions.insertAdjacentHTML('beforeend', `<button class="action-button revision-action" data-row-action="revision" data-id="${id}" title="Kembalikan untuk revisi" aria-label="Kembalikan untuk revisi">↻</button>`); if (!actions.querySelector('[data-row-action="delete"]')) actions.insertAdjacentHTML('beforeend', `<button class="action-button delete-action" data-row-action="delete" data-id="${id}" title="Hapus" aria-label="Hapus">⌫</button>`); } if (status === 'list') actions.querySelector('[data-row-action="complete"]')?.remove(); row.querySelector('.estimate-cell')?.remove(); row.querySelector('.target-cell')?.remove(); row.querySelector('.duration-cell')?.remove(); if (item && status === 'done') { const durationCell = document.createElement('td'); durationCell.className = 'duration-cell'; durationCell.textContent = completionDuration(item); const requestDateCell = row.querySelector('td:nth-child(5)'); if (requestDateCell) requestDateCell.after(durationCell); } }); }
function renderActiveFile() { const label = document.querySelector('#activeFileName'); const state = document.querySelector('#saveState'); const name = openedFileName || 'Draft lokal'; const fileIsDirty = Boolean(openedFileName && hasUnsavedChanges); if (label) { label.innerHTML = `<i class="sync-dot"></i>${escapeHtml(name)}`; label.classList.toggle('is-dirty', fileIsDirty); } if (state) { state.textContent = hasUnsavedChanges ? 'Unsaved changes' : openedFileName ? 'Saved to workbook' : 'Draft lokal'; state.className = `save-state ${hasUnsavedChanges ? 'is-dirty' : ''}`; } }
function importReportMessage() { const { loaded, skippedEmpty, skippedInvalid } = lastImportReport; return `Loaded ${loaded} row${loaded === 1 ? '' : 's'}${skippedEmpty ? ` · ${skippedEmpty} empty skipped` : ''}${skippedInvalid ? ` · ${skippedInvalid} invalid skipped` : ''}`; }
function loadActivities(workbook) { const activitySheet = workbook.SheetNames.find(name => /^activity$/i.test(name)); activities = activitySheet ? XLSX.utils.sheet_to_json(workbook.Sheets[activitySheet]).map(row => ({ date: row.Date || '', action: row.Action || '', title: row.Title || '', requestor: row.Requestor || '', details: row.Details || '' })).filter(activity => activity.action || activity.title || activity.details).reverse() : []; renderActivities(); }
async function loadActivitiesFromFile(file) { const workbook = XLSX.read(await file.arrayBuffer(), { type: 'array' }); const validSheet = workbook.SheetNames.some(name => /request list|ongoing requests|done requests|project list|ongoing projects|done projects|daily tasks|activity|read me/i.test(name)); if (!validSheet) throw new Error('Workbook tidak memiliki sheet REQORD yang dikenali'); loadActivities(workbook); }
async function mergeNotesFromWorkbook(file) { const workbook = XLSX.read(await file.arrayBuffer(), { type: 'array' }); const sheets = workbook.SheetNames.filter(name => /request list|ongoing requests|done requests|daily tasks|project list|ongoing projects|done projects/i.test(name)); sheets.forEach(name => XLSX.utils.sheet_to_json(workbook.Sheets[name]).forEach(row => { const title = String(row.Title || row.Task || '').trim(); const requestor = String(row.Requestor || '').trim(); const item = items.find(candidate => candidate.title === title && (!requestor || candidate.requestor === requestor)); if (item) item.note = String(row.Note || row.Catatan || '').trim(); })); render(); }
function escapeHtml(value) { return String(value).replace(/[&<>'"]/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char])); }
function normalizeItem(item) { return { ...item, title: String(item.title || '').trim(), requestor: String(item.requestor || item.owner || '').trim(), subitems: Array.isArray(item.subitems) ? item.subitems.map((subitem, index) => ({ id: subitem.id || `${item.id}-${index}`, title: String(subitem.title || '').trim(), done: Boolean(subitem.done), order: subitem.order ?? index })).filter(subitem => subitem.title) : [], type: item.type === 'daily' || item.status === 'daily' ? 'daily' : 'project', status: normalizeStatus(item.status), priority: normalizePriority(item.priority), requestDate: normalizeDateValue(item.requestDate), date: normalizeDateValue(item.date || item.targetDone), done: Boolean(item.done), completedAt: item.completedAt || '', dailyDoneDate: item.dailyDoneDate || (item.done && item.type === 'daily' ? today() : '') }; }
function normalizeStatus(value) { const text = String(value || '').toLowerCase(); if (text.includes('daily')) return 'daily'; if (text.includes('preview') || text.includes('review') || text.includes('waiting')) return 'preview'; if (text.includes('revision') || text.includes('revisi')) return 'revision'; if (text.includes('ongoing') || text.includes('progress') || text.includes('kerja')) return 'ongoing'; if (text.includes('done') || text.includes('selesai') || text.includes('complete')) return 'done'; return 'list'; }
function normalizePriority(value) { const text = String(value || 'normal').toLowerCase(); return text.includes('high') || text.includes('penting') ? 'high' : text.includes('low') || text.includes('nanti') ? 'low' : 'normal'; }
function completionDuration(item) { if (!item.completedAt || !item.requestDate) return '—'; const start = new Date(item.requestDate.includes('T') ? item.requestDate : `${item.requestDate}T00:00:00`); const end = new Date(item.completedAt); if (Number.isNaN(start.getTime()) || Number.isNaN(end.getTime())) return '—'; const minutes = Math.max(0, Math.round((end - start) / 60000)); return minutes < 60 ? `${minutes} minutes` : `${Math.round((minutes / 60) * 10) / 10} jam`; }
function durationMinutes(item) { if (!item.completedAt || !item.requestDate) return ''; const start = new Date(item.requestDate.includes('T') ? item.requestDate : `${item.requestDate}T00:00:00`); const end = new Date(item.completedAt); if (Number.isNaN(start.getTime()) || Number.isNaN(end.getTime())) return ''; return Math.max(0, Math.round((end - start) / 60000)); }
function isCompletedRequest(item) { return item?.type === 'project' && (item.status === 'done' || item.done === true || Boolean(item.completedAt)); }
function setCompletedAtFromDuration(item, value, unit) { const amount = Number(value); if (!Number.isFinite(amount) || amount < 0 || !item.requestDate) return ''; const start = new Date(item.requestDate.includes('T') ? item.requestDate : `${item.requestDate}T00:00:00`); const minutes = Math.round(amount * (unit === 'jam' ? 60 : 1)); return new Date(start.getTime() + minutes * 60000).toISOString(); }
function normalizeDateValue(value) { if (!value) return ''; if (value instanceof Date) return `${localDate(value)}T${String(value.getHours()).padStart(2, '0')}:${String(value.getMinutes()).padStart(2, '0')}`; if (typeof value === 'number' && window.XLSX?.SSF) { const parsed = XLSX.SSF.parse_date_code(value); if (parsed) return `${parsed.y}-${String(parsed.m).padStart(2, '0')}-${String(parsed.d).padStart(2, '0')}${parsed.H || parsed.M ? `T${String(parsed.H).padStart(2, '0')}:${String(parsed.M).padStart(2, '0')}` : ''}`; } return String(value).trim().replace(' ', 'T').slice(0, 16); }
function nowDateTime() { const date = new Date(); return `${localDate(date)}T${String(date.getHours()).padStart(2, '0')}:${String(date.getMinutes()).padStart(2, '0')}`; }
function today() { return localDate(new Date()); }
function isDailyDone(item) { return item.type === 'daily' && item.dailyDoneDate === today(); }
function refreshDailyDates() { items.filter(item => item.type === 'daily').forEach(item => { item.requestDate = today(); item.date = today(); item.done = isDailyDone(item); }); }
function scheduleDailyReset() { const nextDay = new Date(); nextDay.setHours(24, 0, 1, 0); setTimeout(() => { items.filter(item => item.type === 'daily' && item.dailyDoneDate !== today()).forEach(item => { item.dailyDoneDate = ''; item.done = false; }); persistDraft(); render(); scheduleDailyReset(); }, nextDay.getTime() - Date.now()); }
function localDate(date) { return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`; }
function dateAfterDays(days, base = today()) { const date = new Date(base.includes('T') ? base : `${base}T00:00:00`); date.setDate(date.getDate() + days); return localDate(date); }
function displayDate(value, includeTime = false) { if (!value) return 'No date'; const date = new Date(value.includes('T') ? value : `${value}T00:00:00`); if (Number.isNaN(date.getTime())) return value; return date.toLocaleDateString('id-ID', { day: 'numeric', month: 'short', ...(includeTime ? { year: 'numeric' } : {}) }) + (includeTime && value.includes('T') ? `, ${date.toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' })}` : ''); }
function targetDoneLabel(value) { if (!value) return '<span class="target-empty">No target</span>'; const target = new Date(`${value}T00:00:00`); const current = new Date(`${today()}T00:00:00`); if (Number.isNaN(target.getTime())) return escapeHtml(value); const days = Math.ceil((target - current) / 86400000); const date = target.toLocaleDateString('id-ID', { day: 'numeric', month: 'short', year: 'numeric' }); const detail = days < 0 ? `Terlambat ${Math.abs(days)} hari` : days === 0 ? 'Hari ini' : days === 1 ? 'Besok' : `${days} hari lagi`; return `<span class="target-date">${escapeHtml(date)}</span><small class="target-detail">${detail}</small>`; }
function urgencyClass() { return ''; }
function requestors() { return [...new Set(items.map(item => item.requestor).filter(Boolean))]; }
function similarityScore(query, name) { if (!query) return 1; if (name === query) return 100; if (name.includes(query)) return 80 - name.indexOf(query); if (query.length < 3) return 0; const matches = [...query].filter(character => name.includes(character)).length; return matches / query.length >= .7 ? 40 - (name.length - query.length) : 0; }
let requestorMatches = [];
let requestorActiveIndex = -1;
function initials(name) { return String(name).split(/\s+/).filter(Boolean).slice(0, 2).map(part => part[0]).join('').toUpperCase(); }
function renderRequestorSuggestions() { const input = document.querySelector('#requestorInput'); const suggestions = document.querySelector('#requestorSuggestions'); const query = input.value.trim().toLowerCase(); if (!query && document.activeElement !== input) { closeRequestorSuggestions(); return; } requestorMatches = requestors().map(name => ({ name, score: similarityScore(query, name.toLowerCase()) })).filter(item => !query || item.score > 0).sort((a, b) => b.score - a.score).slice(0, 6).map(item => item.name); requestorActiveIndex = -1; suggestions.innerHTML = requestorMatches.length ? `<div class="suggestion-heading">${query ? 'Matching requestors' : 'Recent requestors'}<span>${requestorMatches.length}</span></div>${requestorMatches.map((name, index) => `<button type="button" role="option" aria-selected="false" data-index="${index}" data-requestor="${escapeHtml(name)}"><span class="suggestion-avatar">${escapeHtml(initials(name))}</span><span class="suggestion-name">${escapeHtml(name)}</span><span class="suggestion-arrow">↵</span></button>`).join('')}` : `<div class="suggestion-empty">Belum ada requestor yang cocok</div>`; suggestions.hidden = !requestorMatches.length; input.setAttribute('aria-expanded', String(requestorMatches.length > 0)); }
function closeRequestorSuggestions() { const suggestions = document.querySelector('#requestorSuggestions'); const input = document.querySelector('#requestorInput'); suggestions.hidden = true; input.setAttribute('aria-expanded', 'false'); requestorActiveIndex = -1; }
function chooseRequestor(name) { document.querySelector('#requestorInput').value = name; closeRequestorSuggestions(); }
function titleSimilarity(query, title) { const words = query.toLowerCase().split(/\s+/).filter(Boolean); const candidate = title.toLowerCase(); if (!words.length) return 0; return words.filter(word => candidate.includes(word)).length / words.length; }
function renderTitleSuggestions() { const input = document.querySelector('#titleInput'); const suggestions = document.querySelector('#titleSuggestions'); const query = input.value.trim(); if (query.length < 3) { suggestions.hidden = true; return; } const matches = items.map(item => ({ item, score: titleSimilarity(query, item.title) })).filter(match => match.score >= .5).sort((a, b) => b.score - a.score).slice(0, 5); suggestions.innerHTML = matches.length ? `<div class="suggestion-heading">Similar work orders<span>${matches.length}</span></div>${matches.map(({ item }) => `<button type="button" role="option" data-title-id="${item.id}"><span class="suggestion-name">${escapeHtml(item.title)}</span><small>${escapeHtml(groups[item.status] || 'Daily task')} · ${escapeHtml(item.requestor || 'No requestor')}</small></button>`).join('')}` : ''; suggestions.hidden = !matches.length; }
function closeTitleSuggestions() { document.querySelector('#titleSuggestions').hidden = true; }
function render() { const query = document.querySelector('#searchInput').value.trim().toLowerCase(); if (query) doneVisibleLimit = 10; let visible = items.filter(item => (!query || `${item.title} ${item.requestor}`.toLowerCase().includes(query)) && (priorityFilter === 'all' || item.priority === priorityFilter)); visible.sort((a, b) => { if (sortFilter === 'priority') return ['high', 'normal', 'low'].indexOf(a.priority) - ['high', 'normal', 'low'].indexOf(b.priority); if (sortFilter === 'target') return (a.date || '').localeCompare(b.date || ''); const result = (a.requestDate || '').localeCompare(b.requestDate || ''); return sortFilter === 'oldest' ? result : -result; }); Object.keys(tableMap).forEach(status => { const allRows = visible.filter(item => item.type === 'project' && item.status === status); const rows = status === 'done' ? allRows.slice(0, doneVisibleLimit) : allRows; tableMap[status].innerHTML = rows.map(renderRow).join(''); document.querySelector(`#${status}Count`).textContent = items.filter(item => item.type === 'project' && item.status === status).length; document.querySelector(`#${status}Empty`).hidden = rows.length !== 0; if (status === 'done') { const loadMoreButton = document.querySelector('#loadMoreDoneButton'); loadMoreButton.hidden = allRows.length <= 10 || rows.length >= allRows.length; loadMoreButton.textContent = `Load more done works (${Math.min(doneVisibleLimit + 10, allRows.length)}/${allRows.length})`; } }); renderDailyTasks(visible.filter(item => item.type === 'daily')); makeRowsEditable(); removeActionCells(); reorderTableColumns(); normalizeStatusSelects(); enhanceDurationCells(); renderInlineSubitems(); normalizeDailyProgressCells(); document.querySelector('#resultCount').textContent = `${visible.length} of ${items.length}`; renderActiveFile(); renderRequestorSuggestions(); }
function renderRow(item) { const takeButton = item.status === 'list' ? `<button class="action-button take-action" data-row-action="take" data-id="${item.id}" title="Saya mau kerjain" aria-label="Saya mau kerjain">▶</button>` : ''; const completeButton = item.status === 'done' ? '' : `<button class="action-button complete-action" data-row-action="complete" data-id="${item.id}" title="Tandai selesai" aria-label="Tandai selesai">✓</button>`; const revisionButton = item.status === 'done' ? `<button class="action-button revision-action" data-row-action="revision" data-id="${item.id}" title="Kembalikan untuk revisi" aria-label="Kembalikan untuk revisi">↻</button>` : ''; return `<tr class="${urgencyClass(item.date)}"><td class="title-cell">${escapeHtml(item.title)}</td><td>${escapeHtml(item.requestor)}</td><td><select class="status-select status-${item.status}" data-action="status" data-id="${item.id}" aria-label="Status"><option value="list" ${item.status === 'list' ? 'selected' : ''}>Request list</option><option value="ongoing" ${item.status === 'ongoing' ? 'selected' : ''}>Ongoing request</option><option value="done" ${item.status === 'done' ? 'selected' : ''}>Done request</option><option value="daily" ${item.type === 'daily' ? 'selected' : ''}>Daily task</option></select></td><td><select class="priority-select priority-${item.priority}" data-action="priority" data-id="${item.id}" aria-label="Priority"><option value="high" ${item.priority === 'high' ? 'selected' : ''}>High</option><option value="normal" ${item.priority === 'normal' ? 'selected' : ''}>Normal</option><option value="low" ${item.priority === 'low' ? 'selected' : ''}>Low</option></select></td><td>${escapeHtml(displayDate(item.requestDate, true))}</td><td class="target-cell" title="Target done: ${escapeHtml(displayDate(item.date, true))}">${targetDoneLabel(item.date)}</td><td class="row-actions">${takeButton}${completeButton}${revisionButton}<button class="action-button delete-action" data-row-action="delete" data-id="${item.id}" title="Hapus request" aria-label="Hapus request">⌫</button></td></tr>`; }
function renderDailyTasks(tasks) { refreshDailyDates(); const dailyItems = items.filter(item => item.type === 'daily'); document.querySelector('#dailyCount').textContent = dailyItems.length; document.querySelector('#dailyProgress').textContent = `${dailyItems.filter(isDailyDone).length} selesai hari ini`; document.querySelector('#dailyTable').innerHTML = tasks.map(renderDailyRow).join(''); document.querySelector('#dailyEmpty').hidden = tasks.length !== 0; makeRowsEditable(); }
function renderDailyRow(item) { const doneToday = isDailyDone(item); const completeButton = `<button class="action-button complete-action daily-check ${doneToday ? 'daily-done' : ''}" data-row-action="daily-done" data-id="${item.id}" title="${doneToday ? 'Selesai, klik untuk batalkan' : 'Tandai selesai'}" aria-label="${doneToday ? 'Selesai, klik untuk batalkan' : 'Tandai selesai'}" aria-pressed="${doneToday}">${doneToday ? '☑' : '☐'}</button>`; const dailyStatus = `<span class="daily-status-label ${doneToday ? 'is-done' : ''}">${doneToday ? 'Selesai' : 'Belum selesai'}<small>${escapeHtml(displayDate(today(), false))}</small></span>`; return `<tr class="${doneToday ? 'daily-row-done' : ''}"><td class="title-cell ${doneToday ? 'daily-title-done' : ''}">${escapeHtml(item.title)}</td><td>${escapeHtml(item.requestor)}</td><td><select class="status-select status-daily" data-action="status" data-id="${item.id}" aria-label="Status"><option value="daily" selected>Daily task</option><option value="list">Request list</option><option value="ongoing">Ongoing request</option><option value="done">Done request</option></select></td><td><select class="priority-select priority-${item.priority}" data-action="priority" data-id="${item.id}" aria-label="Priority"><option value="high" ${item.priority === 'high' ? 'selected' : ''}>High</option><option value="normal" ${item.priority === 'normal' ? 'selected' : ''}>Normal</option><option value="low" ${item.priority === 'low' ? 'selected' : ''}>Low</option></select></td><td class="daily-status-cell">${dailyStatus}</td><td class="row-actions">${completeButton}<button class="action-button delete-action" data-row-action="delete" data-id="${item.id}" title="Hapus daily task" aria-label="Hapus daily task">⌫</button></td></tr>`; }
function showToast(message) { const toast = document.querySelector('#toast'); toast.textContent = message; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 2400); }
function findItem(id) { return items.find(item => String(item.id) === String(id)); }

document.querySelector('#workOrderForm').addEventListener('submit', event => { event.preventDefault(); const form = new FormData(event.currentTarget); const title = String(form.get('title')).trim(); const requestor = String(form.get('requestor')).trim(); if (!title || !requestor) { document.querySelector('#requestorInput').focus(); showToast('Requestor wajib diisi'); return; } const requestDate = form.get('requestDate') || nowDateTime(); const targetDone = dateAfterDays(3, requestDate); const item = { id: Date.now(), title, requestor, note: '', type: 'project', status: 'list', priority: form.get('priority'), requestDate, date: targetDone, done: false }; items.unshift(item); saveItems(); addActivity('Work order ditambahkan', item); render(); event.currentTarget.reset(); setFormDates(); showToast(`Request masuk ke Request list · target done ${displayDate(targetDone)}`); });
document.querySelector('#searchInput').addEventListener('input', render);
document.querySelector('#titleInput').addEventListener('input', renderTitleSuggestions);
document.querySelector('#titleInput').addEventListener('focus', renderTitleSuggestions);
document.querySelector('#titleSuggestions').addEventListener('pointerdown', event => { const button = event.target.closest('[data-title-id]'); if (!button) return; event.preventDefault(); const item = findItem(button.dataset.titleId); if (item) document.querySelector('#titleInput').value = item.title; closeTitleSuggestions(); });
document.addEventListener('click', event => { if (!event.target.closest('.title-field')) closeTitleSuggestions(); });
document.querySelector('#priorityFilter').addEventListener('change', event => { priorityFilter = event.target.value; render(); });
document.querySelector('#sortFilter').addEventListener('change', event => { sortFilter = event.target.value; render(); });
document.querySelector('#loadMoreDoneButton').addEventListener('click', () => { doneVisibleLimit += 10; render(); });
document.querySelector('#newButton').addEventListener('click', () => { if (hasUnsavedChanges && !window.confirm('Perubahan belum disimpan. Buat draft baru?')) return; addActivity('New draft dibuat', {}, 'Workspace dikosongkan untuk draft baru'); items = []; openedFileHandle = null; openedFileName = ''; hasUnsavedChanges = false; persistDraft(); renderActiveFile(); renderActivities(); render(); showToast('Draft baru dibuat'); });
document.querySelector('#exportButton').addEventListener('click', event => { if (isSaving) { event.stopImmediatePropagation(); return; } isSaving = true; event.currentTarget.disabled = true; });
let editTargetId = null;
const editDialog = document.querySelector('#editDialog');
const noteDialog = document.querySelector('#noteDialog');
let noteTargetId = null;
function openNoteDialog(id) { const item = findItem(id); if (!item) return; noteTargetId = item.id; document.querySelector('#noteDialogTitle').textContent = item.title; document.querySelector('#noteDialogBody').textContent = item.note || 'Belum ada catatan untuk work order ini.'; noteDialog.showModal(); }
document.querySelector('#closeNoteButton').addEventListener('click', () => noteDialog.close()); document.querySelector('#editNoteButton').addEventListener('click', () => { noteDialog.close(); openEditDialog(noteTargetId); setTimeout(() => document.querySelector('#editNoteInput').focus(), 0); }); noteDialog.addEventListener('click', event => { if (event.target === noteDialog) noteDialog.close(); });
const editTitleInput = document.querySelector('#editTitleInput');
const editRequestorInput = document.querySelector('#editRequestorInput');
function openEditDialog(id) { const item = findItem(id); if (!item) return; editTargetId = item.id; editTitleInput.value = item.title; editRequestorInput.value = item.requestor; document.querySelector('#editNoteInput').value = item.note || ''; const isDoneRequest = isCompletedRequest(item); const durationField = document.querySelector('#editDurationField'); durationField.hidden = !isDoneRequest; durationField.classList.toggle('is-visible', isDoneRequest); if (isDoneRequest) durationField.removeAttribute('hidden'); else durationField.setAttribute('hidden', ''); document.querySelector('#editDurationValue').disabled = !isDoneRequest; document.querySelector('#editDurationUnit').disabled = !isDoneRequest; const minutes = durationMinutes(item); document.querySelector('#editDurationUnit').value = minutes && minutes % 60 === 0 ? 'jam' : 'minutes'; document.querySelector('#editDurationValue').value = isDoneRequest && minutes ? minutes / (minutes % 60 === 0 ? 60 : 1) : ''; renderEditSubitems(); editDialog.showModal(); editTitleInput.focus(); }
function renderEditSubitems() { const item = findItem(editTargetId); const list = document.querySelector('#editSubitemList'); if (!list) return; if (!item) { list.innerHTML = ''; return; } item.subitems = Array.isArray(item.subitems) ? item.subitems : []; list.innerHTML = item.subitems.length ? item.subitems.map(subitem => `<div class="subitem-row"><label class="subitem-label"><input type="checkbox" data-edit-subitem-id="${subitem.id}" ${subitem.done ? 'checked' : ''}><span>${escapeHtml(subitem.title)}</span></label><button type="button" class="subitem-delete" data-delete-subitem-id="${subitem.id}" aria-label="Hapus subitem ${escapeHtml(subitem.title)}">×</button></div>`).join('') : '<p class="subitem-empty">Belum ada subitem. Tambahkan di bawah.</p>'; }
function closeEditDialog() { editTargetId = null; editDialog.close(); }
document.querySelector('#editForm').addEventListener('submit', event => { event.preventDefault(); const item = findItem(editTargetId); const title = editTitleInput.value.trim(); const requestor = editRequestorInput.value.trim(); const note = document.querySelector('#editNoteInput').value.trim(); const durationValue = document.querySelector('#editDurationValue').value; const durationUnit = document.querySelector('#editDurationUnit').value; if (!item || !title || !requestor) return; const nextCompletedAt = isCompletedRequest(item) && durationValue !== '' ? setCompletedAtFromDuration(item, durationValue, durationUnit) : item.completedAt; const changed = item.title !== title || item.requestor !== requestor || item.note !== note || nextCompletedAt !== item.completedAt; item.title = title; item.requestor = requestor; item.note = note; item.completedAt = nextCompletedAt; if (changed) { saveItems(); addActivity('Work order diedit', item, 'Title, requestor, Est., atau catatan diperbarui'); } closeEditDialog(); render(); showToast(changed ? 'Work order diperbarui' : 'Tidak ada perubahan'); });
document.querySelector('#deleteFromEditButton').addEventListener('click', () => { const item = findItem(editTargetId); if (!item || !window.confirm(`Delete request "${item.title}"?`)) return; deletedItem = { item, index: items.indexOf(item) }; items = items.filter(candidate => candidate.id !== item.id); saveItems(); addActivity('Request dihapus', item); closeEditDialog(); render(); showToast('Request dihapus · klik Undo dalam 5 detik'); setTimeout(() => { deletedItem = null; }, 5000); });
document.querySelector('#closeEditButton').addEventListener('click', closeEditDialog); document.querySelector('#cancelEditButton').addEventListener('click', closeEditDialog); editDialog.addEventListener('click', event => { if (event.target === editDialog) closeEditDialog(); });
document.querySelector('#editSubitemInput').addEventListener('keydown', event => { if (event.key !== 'Enter') return; event.preventDefault(); const title = event.currentTarget.value.trim(); const item = findItem(editTargetId); if (!item || !title) return; item.subitems = Array.isArray(item.subitems) ? item.subitems : []; item.subitems.push({ id: `${item.id}-${Date.now()}`, title, done: false, order: item.subitems.length }); saveItems(); addActivity('Subitem ditambahkan', item, title); event.currentTarget.value = ''; renderEditSubitems(); render(); });
document.querySelector('#editSubitemList').addEventListener('change', event => { const checkbox = event.target.closest('[data-edit-subitem-id]'); const item = findItem(editTargetId); const subitem = item?.subitems.find(candidate => String(candidate.id) === String(checkbox?.dataset.editSubitemId)); if (!subitem) return; subitem.done = checkbox.checked; saveItems(); addActivity(subitem.done ? 'Subitem selesai' : 'Subitem dibuka lagi', item, subitem.title); renderEditSubitems(); render(); });
document.querySelector('#editSubitemList').addEventListener('click', event => { const button = event.target.closest('[data-delete-subitem-id]'); if (!button) return; const item = findItem(editTargetId); const index = item?.subitems.findIndex(candidate => String(candidate.id) === String(button.dataset.deleteSubitemId)); if (!item || index < 0) return; if (!window.confirm(`Hapus subitem "${item.subitems[index].title}"?`)) return; const [removed] = item.subitems.splice(index, 1); saveItems(); addActivity('Subitem dihapus', item, removed.title); renderEditSubitems(); render(); });
document.querySelector('#requestorInput').addEventListener('input', renderRequestorSuggestions); document.querySelector('#requestorInput').addEventListener('focus', renderRequestorSuggestions); document.querySelector('#requestorInput').addEventListener('keydown', event => { if (!requestorMatches.length) return; if (event.key === 'ArrowDown' || event.key === 'ArrowUp') { event.preventDefault(); requestorActiveIndex = (requestorActiveIndex + (event.key === 'ArrowDown' ? 1 : requestorMatches.length - 1)) % requestorMatches.length; document.querySelectorAll('#requestorSuggestions [data-requestor]').forEach((button, index) => button.classList.toggle('active', index === requestorActiveIndex)); } if (event.key === 'Enter' && requestorActiveIndex >= 0) { event.preventDefault(); chooseRequestor(requestorMatches[requestorActiveIndex]); } if (event.key === 'Escape') closeRequestorSuggestions(); }); document.querySelector('#requestorSuggestions').addEventListener('pointerdown', event => { const button = event.target.closest('[data-requestor]'); if (!button) return; event.preventDefault(); event.stopPropagation(); chooseRequestor(button.dataset.requestor); }); document.addEventListener('click', event => { if (!event.target.closest('.requestor-field')) closeRequestorSuggestions(); });
document.addEventListener('keydown', event => { if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === 'k') { event.preventDefault(); document.querySelector('#titleInput').focus(); } if (event.key === 'Escape') closeRequestorSuggestions(); });
const profileDialog = document.querySelector('#profileDialog');
document.querySelector('#makerButton').addEventListener('click', () => profileDialog.showModal());
document.querySelector('#closeProfileButton').addEventListener('click', () => profileDialog.close());
profileDialog.addEventListener('click', event => { if (event.target === profileDialog) profileDialog.close(); });
document.querySelectorAll('[data-maker-tab]').forEach(tab => tab.addEventListener('click', () => { document.querySelectorAll('[data-maker-tab]').forEach(button => button.classList.toggle('active', button === tab)); document.querySelectorAll('[data-maker-content]').forEach(content => { content.hidden = content.dataset.makerContent !== tab.dataset.makerTab; }); }));
document.querySelector('[data-maker-content="recent"] .maker-changelog h3').insertAdjacentHTML('afterend', '<div class="changelog-meta"><strong>v0.2.0</strong><span>Updated · 21 Sep 2026</span></div>');
document.querySelector('.profile-footer span').innerHTML = '<i class="sync-dot"></i> REQORD v0.2.0';
const fallbackRecentCommits = [
  ['3876cd2', '2026-09-21', 'Clarify daily completion labels'],
  ['54b26ce', '2026-09-21', 'Suggest similar work order titles'],
  ['b2956fb', '2026-09-21', 'Fix duplicate delete icon'],
  ['56bcd58', '2026-09-21', 'Increase request table typography'],
  ['df693c5', '2026-09-21', 'Improve add button readability'],
  ['c61b6d3', '2026-09-21', 'Use canonical workbook writer'],
  ['77a2ba1', '2026-09-21', 'Harden repository and workbook save flow'],
  ['c27d931', '2026-09-21', 'Add REQORD monogram favicon'],
  ['eb65fc8', '2026-09-21', 'Show recent changes in maker modal'],
  ['e509b67', '2026-09-21', 'Align primary button icon text'],
  ['f119ebf', '2026-09-21', 'Reduce add work order button text size'],
  ['22bedaf', '2026-09-21', 'Ensure add work order icon visibility'],
  ['7f22eb9', '2026-09-21', 'Center add work order button content'],
  ['55fa92a', '2026-09-21', 'Refine add work order controls'],
  ['d518aaa', '2026-09-21', 'Reset daily checkboxes at midnight'],
  ['3fd8ba1', '2026-09-21', 'Standardize thin focus states'],
  ['7283274', '2026-09-21', 'Add modal editing for work orders'],
  ['d37d116', '2026-09-21', 'Complete history and activity audit log'],
  ['ebaf49b', '2026-09-21', 'Prevent zero-byte workbook saves'],
  ['defa611', '2026-09-21', 'Record MVP reliability checkpoint status'],
  ['62b47c2', '2026-09-21', 'Harden draft storage and regression checks'],
  ['99f1750', '2026-09-21', 'Improve MVP reliability and editing flow'],
  ['e5ad452', '2026-09-21', 'Widen maker changelog modal'],
  ['57e5364', '2026-09-21', 'Add version and commit date to changelog'],
  ['d9d221d', '2026-09-21', 'Show complete changelog in maker modal'],
  ['2be435a', '2026-09-21', 'Match maker credit font'],
  ['202a30a', '2026-09-21', 'Make only maker name interactive'],
  ['20f2f53', '2026-09-21', 'Refine maker footer credit'],
  ['1a87863', '2026-09-21', 'Format activity timestamps locally'],
  ['6fc5f54', '2026-09-21', 'Remove default Excel sheets on save'],
  ['9d15acb', '2026-09-21', 'Add maker profile and changelog modal'],
  ['1599353', '2026-09-21', 'Simplify settings panel'],
  ['8b4ff76', '2026-09-21', 'Fix save picker handle assignment'],
  ['a00eb6c', '2026-09-21', 'Make save and save-as-new reliable'],
  ['c80c617', '2026-09-21', 'Request workbook write permission before save'],
  ['daf002c', '2026-09-21', 'Show saved draft filename'],
  ['bb7eb49', '2026-09-21', 'Show active workbook name in toolbar'],
  ['5910349', '2026-09-21', 'Fix workbook load activity reader'],
  ['6003d49', '2026-09-21', 'Add local drafts and workbook save modes'],
  ['0d53ae6', '2026-09-21', 'Load activity history from workbook'],
  ['3af0153', '2026-09-21', 'Add history activity panel and export log'],
  ['0a3188b', '2026-09-20', 'Warn before losing unsaved workbook changes'],
  ['cd9f800', '2026-09-20', 'Respect hidden state for load more button'],
  ['42df10d', '2026-09-20', 'Hide done load more when unnecessary'],
  ['a251d74', '2026-09-20', 'Paginate done requests list'],
  ['46ad929', '2026-09-20', 'Refine daily checkbox stroke weight'],
  ['8504410', '2026-09-20', 'Rename daily task date columns'],
  ['e8afdd6', '2026-09-20', 'Reset daily task dates each day'],
  ['bc2db81', '2026-09-20', 'Clarify daily task completion state'],
  ['a0bf74e', '2026-09-20', 'Use icon for daily task completion'],
  ['85f178a', '2026-09-20', 'Make daily tasks reset each day'],
  ['480d4be', '2026-09-20', 'Enable replacing opened Excel workbooks'],
  ['426bcb2', '2026-09-20', 'Fix template loading and save fallback'],
  ['e36900a', '2026-09-20', 'Add downloadable Excel table template'],
  ['db06391', '2026-09-20', 'Require opening workbook before saving data'],
  ['4394723', '2026-09-20', 'Initial REQORD work order prototype']
];
const recentGroup = document.querySelector('[data-maker-content="recent"] .changelog-group');
function renderRecentCommits(commits) { if (recentGroup) recentGroup.innerHTML = `<strong>All commits</strong><ul class="commit-list">${commits.map(([hash, date, message]) => `<li><code>${escapeHtml(hash)}</code><span>${escapeHtml(date)}</span><b>${escapeHtml(message)}</b></li>`).join('')}</ul>`; }
renderRecentCommits(fallbackRecentCommits);
fetch('recent-changes.json', { cache: 'no-store' }).then(response => response.ok ? response.json() : Promise.reject()).then(renderRecentCommits).catch(() => {});
const activityPanel = document.querySelector('#activityPanel');
document.querySelector('#activityButton').addEventListener('click', () => { activityPanel.classList.add('open'); activityPanel.setAttribute('aria-hidden', 'false'); });
document.querySelector('#closeActivityButton').addEventListener('click', () => { activityPanel.classList.remove('open'); activityPanel.setAttribute('aria-hidden', 'true'); });
function downloadTemplate() { if (!window.XLSX) { showToast('Library XLSX belum tersedia'); return; } const workbook = XLSX.utils.book_new(); const requestHeaders = ['Title', 'Requestor', 'Status', 'Priority', 'RequestDate', 'TargetDone']; const sheets = { 'Request List': requestHeaders, 'Ongoing Requests': requestHeaders, 'Done Requests': requestHeaders, 'Daily Tasks': ['Task', 'Requestor', 'Date', 'Priority', 'Done'] }; Object.entries(sheets).forEach(([name, headers]) => { const sheet = XLSX.utils.aoa_to_sheet([headers, headers[0] === 'Title' ? ['Contoh work order (hapus baris ini)', '', 'Request list', 'Normal', '', ''] : ['Contoh daily task (hapus baris ini)', '', '', 'Normal', 'No']]); sheet['!autofilter'] = { ref: `A1:${String.fromCharCode(64 + headers.length)}1` }; sheet['!cols'] = headers.map(header => ({ wch: header === 'Title' || header === 'Task' ? 42 : header === 'Requestor' ? 22 : 16 })); XLSX.utils.book_append_sheet(workbook, sheet, name); }); const readMe = XLSX.utils.aoa_to_sheet([['REQORD WORK ORDER TEMPLATE'], ['Isi data di sheet yang sesuai, hapus baris contoh, lalu buka file ini melalui Open file di REQORD.'], [''], ['Sheet', 'Keterangan'], ['Request List', 'Request baru yang belum dikerjakan'], ['Ongoing Requests', 'Request yang sedang dikerjakan'], ['Done Requests', 'Request yang sudah selesai'], ['Daily Tasks', 'Pekerjaan rutin; Done diisi Yes atau No'], [''], ['Kolom request', 'Title, Requestor, Status, Priority, RequestDate, TargetDone'], ['Kolom daily task', 'Task, Requestor, Date, Priority, Done']]); readMe['!cols'] = [{ wch: 24 }, { wch: 78 }]; XLSX.utils.book_append_sheet(workbook, readMe, 'Read me'); const file = XLSX.write(workbook, { bookType: 'xlsx', type: 'array' }); const url = URL.createObjectURL(new Blob([file], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' })); const link = document.createElement('a'); link.href = url; link.download = 'REQORD-table-template.xlsx'; link.click(); URL.revokeObjectURL(url); showToast('Template table berhasil diunduh'); }
document.querySelector('.table-stack').addEventListener('change', event => { const control = event.target; const item = findItem(control.dataset.id); if (!item) return; if (control.dataset.action === 'status') { item.status = normalizeStatus(control.value); item.type = item.status === 'daily' ? 'daily' : 'project'; if (item.status === 'done') { item.done = true; item.completedAt = item.completedAt || new Date().toISOString(); } } else if (control.dataset.action === 'priority') item.priority = control.value; else return; saveItems(); addActivity(control.dataset.action === 'priority' ? 'Priority diubah' : `Status menjadi ${item.status}`, item); render(); showToast(item.type === 'daily' ? 'Dipindahkan ke Daily tasks' : item.status === 'done' ? 'Request selesai' : 'Request diperbarui'); });
let deleteTargetId = null;
const deleteDialog = document.querySelector('#deleteDialog');
const deleteConfirmInput = document.querySelector('#deleteConfirmInput');
const confirmDeleteButton = document.querySelector('#confirmDeleteButton');
function openDeleteDialog(id) { deleteTargetId = id; deleteConfirmInput.value = ''; confirmDeleteButton.disabled = true; deleteDialog.showModal(); setTimeout(() => deleteConfirmInput.focus(), 0); }
function closeDeleteDialog() { deleteTargetId = null; deleteDialog.close(); }
document.querySelector('.table-stack').addEventListener('click', event => { const button = event.target.closest('[data-row-action]'); if (!button) return; const item = findItem(button.dataset.id); if (!item) return; if (button.dataset.rowAction === 'daily-done') { item.dailyDoneDate = isDailyDone(item) ? '' : today(); saveItems(); addActivity(item.dailyDoneDate ? 'Daily task selesai hari ini' : 'Daily task dibuka lagi', item); render(); showToast(item.dailyDoneDate ? 'Daily task selesai hari ini' : 'Daily task dibuka lagi'); return; } if (button.dataset.rowAction === 'take') { item.status = 'ongoing'; item.type = 'project'; item.done = false; saveItems(); addActivity('Request mulai dikerjakan', item); render(); showToast('Saya kerjain request ini'); return; } if (button.dataset.rowAction === 'complete') { item.status = 'done'; item.type = 'project'; item.done = true; saveItems(); addActivity('Request selesai', item); render(); showToast('Request ditandai selesai'); return; } if (button.dataset.rowAction === 'revision') { item.status = 'ongoing'; item.type = 'project'; item.done = false; saveItems(); addActivity('Request dikembalikan untuk revisi', item); render(); showToast('Request dikembalikan untuk revisi'); return; } if (button.dataset.rowAction === 'delete') openDeleteDialog(item.id); });
deleteConfirmInput.addEventListener('input', () => { confirmDeleteButton.disabled = deleteConfirmInput.value.trim().toLowerCase() !== 'saya sudah pikirin'; });
confirmDeleteButton.addEventListener('click', () => { if (confirmDeleteButton.disabled || deleteTargetId === null) return; const item = findItem(deleteTargetId); deletedItem = { item, index: items.indexOf(item) }; items = items.filter(candidate => candidate.id !== deleteTargetId); saveItems(); addActivity('Request dihapus', item); closeDeleteDialog(); render(); showToast('Request dihapus · klik Undo dalam 5 detik'); setTimeout(() => { deletedItem = null; }, 5000); });
document.querySelector('#toast').addEventListener('click', () => { if (!deletedItem) return; items.splice(Math.max(0, deletedItem.index), 0, deletedItem.item); saveItems(); addActivity('Request dipulihkan', deletedItem.item); deletedItem = null; render(); showToast('Request dipulihkan'); });
document.querySelector('#closeDeleteButton').addEventListener('click', closeDeleteDialog); document.querySelector('#cancelDeleteButton').addEventListener('click', closeDeleteDialog); deleteDialog.addEventListener('click', event => { if (event.target === deleteDialog) closeDeleteDialog(); });
document.querySelector('.table-stack').addEventListener('click', event => { const button = event.target.closest('[data-row-action="edit"]'); if (button) { event.stopPropagation(); openEditDialog(button.dataset.id); } });
document.querySelector('.table-stack').addEventListener('click', event => { const button = event.target.closest('[data-duration-edit-id]'); if (button) { event.stopPropagation(); openEditDialog(button.dataset.durationEditId); } });
document.querySelector('.table-stack').addEventListener('click', event => { const button = event.target.closest('[data-row-action="note"]'); if (button) { event.stopPropagation(); openNoteDialog(button.dataset.id); } });
document.querySelector('.table-stack').addEventListener('click', event => { const title = event.target.closest('.title-cell.has-note'); if (title) openNoteDialog(title.dataset.noteId); });
document.querySelector('.table-stack').addEventListener('click', event => { const note = event.target.closest('.note-cell.has-note'); if (note) openNoteDialog(note.dataset.noteId); });
document.querySelector('.table-stack').addEventListener('keydown', event => { const title = event.target.closest('.title-cell.has-note'); if (title && (event.key === 'Enter' || event.key === ' ')) { event.preventDefault(); openNoteDialog(title.dataset.noteId); } });
const subitemDialog = document.querySelector('#subitemDialog'); let subitemTargetId = null;
function openSubitemDialog(id) { const item = findItem(id); if (!item) return; subitemTargetId = item.id; document.querySelector('#subitemDialogTitle').textContent = `Subitems · ${item.title}`; subitemDialog.showModal(); document.querySelector('#subitemInput').focus(); }
document.querySelector('#subitemInput').addEventListener('keydown', event => { if (event.key !== 'Enter') return; event.preventDefault(); const title = event.currentTarget.value.trim(); const item = findItem(subitemTargetId); if (!item || !title) return; item.subitems = Array.isArray(item.subitems) ? item.subitems : []; item.subitems.push({ id: `${item.id}-${Date.now()}`, title, done: false, order: item.subitems.length }); saveItems(); addActivity('Subitem ditambahkan', item, title); event.currentTarget.value = ''; render(); });
document.querySelector('.table-stack').addEventListener('change', event => { const checkbox = event.target.closest('[data-inline-subitem-id]'); if (!checkbox) return; const item = findItem(checkbox.dataset.inlineSubitemParent); const subitem = item?.subitems.find(candidate => String(candidate.id) === String(checkbox.dataset.inlineSubitemId)); if (!subitem) return; subitem.done = checkbox.checked; saveItems(); addActivity(subitem.done ? 'Subitem selesai' : 'Subitem dibuka lagi', item, subitem.title); render(); });
document.querySelector('#closeSubitemButton').addEventListener('click', () => subitemDialog.close()); subitemDialog.addEventListener('click', event => { if (event.target === subitemDialog) subitemDialog.close(); });
document.querySelector('.table-stack').addEventListener('click', event => { const title = event.target.closest('.title-cell.has-subitems'); if (title) openEditDialog(title.dataset.subitemId); }); document.querySelector('.table-stack').addEventListener('keydown', event => { const title = event.target.closest('.title-cell.has-subitems'); if (title && (event.key === 'Enter' || event.key === ' ')) { event.preventDefault(); openEditDialog(title.dataset.subitemId); } });
document.querySelector('.table-stack').addEventListener('click', event => { const button = event.target.closest('[data-row-action="complete"]'); if (button) { const item = findItem(button.dataset.id); if (item && !item.completedAt) item.completedAt = new Date().toISOString(); } }, true);
async function loadWorkbook(file) { if (!window.XLSX) throw new Error('XLSX unavailable'); const workbook = XLSX.read(await file.arrayBuffer(), { type: 'array' }); const sourceSheets = workbook.SheetNames.filter(name => /request list|ongoing requests|done requests|project list|ongoing projects|done projects/i.test(name)); const dailySheet = workbook.SheetNames.find(name => /daily tasks/i.test(name)); const rows = (sourceSheets.length ? sourceSheets : workbook.SheetNames.slice(0, 1)).flatMap(sheetName => XLSX.utils.sheet_to_json(workbook.Sheets[sheetName]).map(row => ({ ...row, __sheetStatus: sheetName }))); const imported = rows.map((row, index) => { const requestDate = normalizeDateValue(row.RequestDate || row.requestDate) || today(); const sheetStatus = /ongoing/i.test(row.__sheetStatus) ? 'ongoing' : /done/i.test(row.__sheetStatus) ? 'done' : 'list'; return normalizeItem({ id: Date.now() + index, title: row.Title || row.title || row.Name || `Imported request ${index + 1}`, requestor: row.Requestor || row.requestor || row.Owner || row.owner, type: 'project', status: row.Status ? normalizeStatus(row.Status) : sheetStatus, priority: normalizePriority(row.Priority), requestDate, date: normalizeDateValue(row.TargetDone || row.targetDone || row.Deadline || row.deadline) || dateAfterDays(3, requestDate) }); }); if (dailySheet) { const dailyRows = XLSX.utils.sheet_to_json(workbook.Sheets[dailySheet]); dailyRows.forEach((row, index) => imported.push(normalizeItem({ id: Date.now() + imported.length + index, title: row.Task || row.Title, requestor: row.Requestor, type: 'daily', status: 'daily', priority: normalizePriority(row.Priority), requestDate: normalizeDateValue(row.Date || row.RequestDate) || today(), date: dateAfterDays(3, normalizeDateValue(row.Date || row.RequestDate) || today()), done: String(row.Done || '').toLowerCase() === 'yes' || String(row.Done || '').toLowerCase() === 'true' }))); } if (!imported.length) throw new Error('empty'); items = imported; saveItems(); render(); document.querySelector('#exportButton').disabled = false; document.querySelector('#exportButton').title = `Save changes to ${openedFileName || 'this file'}`; showToast(`${imported.length} item loaded`); }
document.querySelector('#importButton').addEventListener('click', async () => { if (hasUnsavedChanges && !window.confirm('Perubahan belum disimpan akan diganti oleh workbook baru. Lanjutkan Load?')) return; try { isLoadingWorkbook = true; if (window.showOpenFilePicker) { [openedFileHandle] = await window.showOpenFilePicker({ types: [{ description: 'Excel workbook', accept: { 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet': ['.xlsx'] } }], multiple: false }); const file = await openedFileHandle.getFile(); openedFileName = file.name; renderActiveFile(); await loadActivitiesFromFile(file); await loadWorkbook(file); await mergeNotesFromWorkbook(file); hasUnsavedChanges = false; addActivity('Workbook di-load', {}, openedFileName); renderActiveFile(); showToast(`${openedFileName} · ${importReportMessage()}`); } else document.querySelector('#fileInput').click(); } catch (error) { if (error.name !== 'AbortError') showToast(`Load gagal: ${error.message || 'periksa file Excel'}`); } finally { isLoadingWorkbook = false; } });
document.querySelector('#fileInput').addEventListener('change', async event => { const file = event.target.files[0]; if (!file) return; openedFileHandle = null; openedFileName = file.name; renderActiveFile(); try { isLoadingWorkbook = true; await loadActivitiesFromFile(file); await loadWorkbook(file); await mergeNotesFromWorkbook(file); hasUnsavedChanges = false; addActivity('Workbook di-load', {}, openedFileName); renderActiveFile(); showToast(`${openedFileName} · ${importReportMessage()}`); } catch (error) { showToast(`Load gagal: ${error.message || 'periksa file Excel'}`); } finally { isLoadingWorkbook = false; } event.target.value = ''; });
document.querySelector('#exportButton').addEventListener('click', () => { if (!window.XLSX) { showToast('Library XLSX belum tersedia'); return; } const rows = items.filter(item => item.type === 'project').map(item => ({ Title: item.title, Requestor: item.requestor, Status: groups[item.status], Priority: item.priority, RequestDate: item.requestDate || '', TargetDone: item.date })); const workbook = XLSX.utils.book_new(); const readMe = [['REQORD WORK ORDER FILE'], ['Edit file ini di Excel, lalu buka kembali dengan Open file di REQORD.'], [''], ['Kolom', 'Keterangan'], ['Title', 'Judul request atau daily task'], ['Requestor', 'Nama pengaju'], ['Status', 'Request list, Ongoing request, atau Done request'], ['Priority', 'High, Normal, atau Low'], ['RequestDate', 'Tanggal dan jam dibuat'], ['TargetDone', 'Target selesai otomatis tiga hari setelah RequestDate'], ['Daily Tasks', 'Task rutin; gunakan kolom Done bernilai Yes atau No']]; const sheets = { 'Request List': 'list', 'Ongoing Requests': 'ongoing', 'Done Requests': 'done' }; Object.entries(sheets).forEach(([sheetName, status]) => { const sheetRows = rows.filter(row => row.Status === groups[status]); const sheet = XLSX.utils.json_to_sheet(sheetRows, { header: ['Title', 'Requestor', 'Status', 'Priority', 'RequestDate', 'TargetDone'] }); sheet['!autofilter'] = { ref: `A1:F${Math.max(sheetRows.length + 1, 1)}` }; sheet['!cols'] = [{ wch: 48 }, { wch: 22 }, { wch: 20 }, { wch: 12 }, { wch: 22 }, { wch: 16 }]; XLSX.utils.book_append_sheet(workbook, sheet, sheetName); }); const dailyRows = items.filter(item => item.type === 'daily').map(task => ({ Task: task.title, Requestor: task.requestor, Date: task.requestDate, Priority: task.priority, Done: task.done ? 'Yes' : 'No' })); const dailySheet = XLSX.utils.json_to_sheet(dailyRows, { header: ['Task', 'Requestor', 'Date', 'Priority', 'Done'] }); dailySheet['!autofilter'] = { ref: `A1:E${Math.max(dailyRows.length + 1, 1)}` }; dailySheet['!cols'] = [{ wch: 48 }, { wch: 22 }, { wch: 22 }, { wch: 12 }, { wch: 10 }]; XLSX.utils.book_append_sheet(workbook, dailySheet, 'Daily Tasks'); XLSX.utils.book_append_sheet(workbook, XLSX.utils.aoa_to_sheet(readMe), 'Read me'); XLSX.writeFile(workbook, `reqord-work-orders-${new Date().toISOString().slice(0, 10)}.xlsx`); showToast(`${items.length} item disimpan ke Excel`); });
window.addEventListener('beforeunload', event => { if (!hasUnsavedChanges) return; event.preventDefault(); event.returnValue = 'Perubahan belum disimpan. Simpan dulu sebelum keluar?'; });
function normalizeWorkbookDateCells(workbook) { const dataSheets = workbook.SheetNames.filter(name => !/^activity$|^read me$|^subitems$/i.test(name)); dataSheets.forEach(name => { const sheet = workbook.Sheets[name]; const rows = XLSX.utils.sheet_to_json(sheet); if (rows.length) { const enriched = rows.map(row => { const title = String(row.Title || row.Task || '').trim(); const requestor = String(row.Requestor || '').trim(); const item = items.find(candidate => candidate.title === title && (!requestor || candidate.requestor === requestor)); return { ...row, Note: item?.note || row.Note || '' }; }); workbook.Sheets[name] = XLSX.utils.json_to_sheet(enriched); } }); const subitemRows = items.flatMap(item => (item.subitems || []).map((subitem, index) => ({ ParentID: item.id, WorkOrder: item.title, Subitem: subitem.title, Done: subitem.done ? 'Yes' : 'No', Order: subitem.order ?? index }))); const subitemSheet = XLSX.utils.json_to_sheet(subitemRows, { header: ['ParentID', 'WorkOrder', 'Subitem', 'Done', 'Order'] }); subitemSheet['!autofilter'] = { ref: `A1:E${Math.max(subitemRows.length + 1, 1)}` }; subitemSheet['!cols'] = [{ wch: 18 }, { wch: 48 }, { wch: 48 }, { wch: 10 }, { wch: 10 }]; if (workbook.SheetNames.includes('Subitems')) workbook.Sheets.Subitems = subitemSheet; else XLSX.utils.book_append_sheet(workbook, subitemSheet, 'Subitems'); workbook.SheetNames.forEach(name => { const sheet = workbook.Sheets[name]; Object.keys(sheet).forEach(address => { if (address[0] === '!') return; const cell = sheet[address]; if (typeof cell.v === 'string' && /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}/.test(cell.v)) cell.v = cell.v.replace('T', ' '); }); }); }
function addActivitySheet(workbook) { addActivity('Workbook disimpan', {}, openedFileName || 'Draft lokal'); removeDefaultSheets(workbook); const rows = activities.map(activity => ({ Date: activity.date, Action: activity.action, Title: activity.title, Requestor: activity.requestor, Details: activity.details || '' })); const sheet = XLSX.utils.json_to_sheet(rows, { header: ['Date', 'Action', 'Title', 'Requestor', 'Details'] }); sheet['!autofilter'] = { ref: `A1:E${Math.max(rows.length + 1, 1)}` }; sheet['!cols'] = [{ wch: 20 }, { wch: 32 }, { wch: 48 }, { wch: 22 }, { wch: 48 }]; if (workbook.SheetNames.includes('Activity')) workbook.Sheets.Activity = sheet; else XLSX.utils.book_append_sheet(workbook, sheet, 'Activity'); normalizeWorkbookDateCells(workbook); }
function removeDefaultSheets(workbook) { workbook.SheetNames = workbook.SheetNames.filter(name => !/^(sheet\s*1|sheet\s*2|sheet\s*3)$/i.test(name.trim())); getWorkbookBytes(workbook); }
const originalWriteFile = window.XLSX?.writeFile;
function getWorkbookBytes(workbook) { const bytes = XLSX.write(workbook, { bookType: 'xlsx', type: 'array' }); if (!bytes || !bytes.byteLength) throw new Error('Workbook kosong atau gagal dibuat'); return bytes; }
function downloadWorkbook(workbook, filename) { const bytes = getWorkbookBytes(workbook); const url = URL.createObjectURL(new Blob([bytes], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' })); const link = document.createElement('a'); link.href = url; link.download = filename; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
async function ensureWritePermission() { if (!openedFileHandle) return false; if (openedFileHandle.queryPermission && await openedFileHandle.queryPermission({ mode: 'readwrite' }) === 'granted') return true; if (openedFileHandle.requestPermission) return await openedFileHandle.requestPermission({ mode: 'readwrite' }) === 'granted'; return true; }
async function writeWorkbookToHandle(workbook, handle) { const bytes = getWorkbookBytes(workbook); const writable = await handle.createWritable(); try { await writable.write(bytes); await writable.close(); return bytes.byteLength; } catch (error) { try { await writable.abort(); } catch {} throw error; } }
if (originalWriteFile) window.XLSX.writeFile = async workbook => { try { addActivitySheet(workbook); const filename = saveAsRequested ? 'REQORD-work-orders.xlsx' : (openedFileName || 'REQORD-work-orders.xlsx'); if (saveAsRequested) { if (window.showSaveFilePicker) { openedFileHandle = await window.showSaveFilePicker({ suggestedName: filename, types: [{ description: 'Excel workbook', accept: { 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet': ['.xlsx'] } }] }); openedFileName = openedFileHandle.name; await ensureWritePermission(); await writeWorkbookToHandle(workbook, openedFileHandle); } else downloadWorkbook(workbook, filename); } else if (openedFileHandle && await ensureWritePermission()) { await writeWorkbookToHandle(workbook, openedFileHandle); } else if (window.showSaveFilePicker) { openedFileHandle = await window.showSaveFilePicker({ suggestedName: filename, types: [{ description: 'Excel workbook', accept: { 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet': ['.xlsx'] } }] }); openedFileName = openedFileHandle.name; await writeWorkbookToHandle(workbook, openedFileHandle); } else { openedFileName = filename; downloadWorkbook(workbook, openedFileName); } hasUnsavedChanges = false; persistDraft(); renderActiveFile(); showToast(`${openedFileName} berhasil disimpan`); } catch (error) { if (error.name === 'AbortError') return; showToast(`Save gagal: ${error.message || 'browser menolak akses file'}`); } finally { isSaving = false; const saveButton = document.querySelector('#exportButton'); if (saveButton) saveButton.disabled = false; renderActiveFile(); } };
async function parseWorkbook(file) { if (!window.XLSX) throw new Error('XLSX unavailable'); const workbook = XLSX.read(await file.arrayBuffer(), { type: 'array' }); const requestSheets = workbook.SheetNames.filter(name => /request list|ongoing requests|done requests|project list|ongoing projects|done projects/i.test(name)); const dailySheet = workbook.SheetNames.find(name => /daily tasks/i.test(name)); const recognized = requestSheets.length > 0 || Boolean(dailySheet) || workbook.SheetNames.some(name => /^activity$|^read me$/i.test(name)); if (!recognized) throw new Error('Workbook tidak memiliki sheet REQORD yang dikenali'); const report = { loaded: 0, skippedEmpty: 0, skippedInvalid: 0 }; const imported = []; requestSheets.forEach(sheetName => XLSX.utils.sheet_to_json(workbook.Sheets[sheetName]).forEach((row, index) => { const title = String(row.Title || row.title || row.Name || '').trim(); if (!title) { report.skippedEmpty += 1; return; } const requestDate = normalizeDateValue(row.RequestDate || row.requestDate) || today(); const sheetStatus = /ongoing/i.test(sheetName) ? 'ongoing' : /done/i.test(sheetName) ? 'done' : 'list'; imported.push(normalizeItem({ id: Date.now() + imported.length + index, title, requestor: row.Requestor || row.requestor || row.Owner || row.owner, type: 'project', status: row.Status ? normalizeStatus(row.Status) : sheetStatus, priority: normalizePriority(row.Priority), requestDate, date: normalizeDateValue(row.TargetDone || row.targetDone || row.Deadline || row.deadline) || dateAfterDays(3, requestDate) })); report.loaded += 1; })); if (dailySheet) XLSX.utils.sheet_to_json(workbook.Sheets[dailySheet]).forEach((row, index) => { const title = String(row.Task || row.Title || '').trim(); if (!title) { report.skippedEmpty += 1; return; } imported.push(normalizeItem({ id: Date.now() + imported.length + index, title, requestor: row.Requestor, type: 'daily', status: 'daily', priority: normalizePriority(row.Priority), requestDate: today(), date: today(), done: String(row.Done || '').toLowerCase() === 'yes' || String(row.Done || '').toLowerCase() === 'true' })); report.loaded += 1; }); return { items: imported, report }; }
loadWorkbook = async file => { const result = await parseWorkbook(file); items = result.items; const workbook = XLSX.read(await file.arrayBuffer(), { type: 'array' }); const subitemSheet = workbook.SheetNames.find(name => /^subitems$/i.test(name)); if (subitemSheet) XLSX.utils.sheet_to_json(workbook.Sheets[subitemSheet]).forEach(row => { const item = items.find(candidate => String(candidate.id) === String(row.ParentID)) || items.find(candidate => candidate.title === String(row.WorkOrder || '').trim()); if (item && row.Subitem) { item.subitems = Array.isArray(item.subitems) ? item.subitems : []; item.subitems.push({ id: `${item.id}-${row.Order || item.subitems.length}`, title: String(row.Subitem), done: String(row.Done || '').toLowerCase() === 'yes' || String(row.Done || '').toLowerCase() === 'true', order: Number(row.Order) || item.subitems.length }); } }); lastImportReport = result.report; isLoadingWorkbook = true; saveItems(); isLoadingWorkbook = false; render(); document.querySelector('#exportButton').disabled = false; };
function setFormDates() { document.querySelector('#requestDateInput').value = nowDateTime(); }
setFormDates(); openDraftDatabase(); renderActiveFile(); renderActivities(); render(); scheduleDailyReset();
